// src/components/bookmarks/BookmarkFormDialog.vue
<script setup lang="ts">
import BookmarkIcon from '@/components/BookmarkIcon.vue'

const {
  showAdd,
  modalTitle,
  draft,
  draftLocations,
  previewIcon,
  showCategorySelector,
  showIconSelector,
  formError,
  isSaving,
  iconLoading,
  iconFetchFailed,
  maxDescLen,
  selectedLocationsLabel,
  handleSave,
  askAI,
  aiEnabled,
  canUseAi,
  aiUnavailableReason,
  saveButtonLabel,
  aiBackgroundTooltip,
  undoTitle,
  undoDesc,
  hasAIGenerated,
  isUrlAccessible,
  isCheckingUrl,
  isGenerating,
  isSuggestingCategory,
  categorySuggestion,
  onTitleInput,
  onDescInput,
  askCategorySuggestion,
  applyCategorySuggestion,
  dismissCategorySuggestion,
  requestDelete,
  editingId
} = useBookmarkForm()

const emit = defineEmits<{
  close: []
}>()

const onSave = async () => {
  await handleSave()
}

const onAiBackgroundSave = async () => {
  await handleSave({ forceAi: true, background: true })
}

const handleClose = () => {
  emit('close')
}
</script>

<template>
  <div class="bookmark-form-page flex flex-col h-full bg-background relative z-10">
    <!-- Header -->
    <header class="shrink-0 z-30 flex items-center gap-4 px-6 pt-5 pb-3">
      <Button variant="outline" size="icon" class="h-10 w-10 shrink-0 rounded-xl bg-background/80" @click="handleClose">
        <span class="i-ph-arrow-left-thin text-lg" />
      </Button>
      <div class="flex items-center gap-3">
        <span class="flex h-9 w-9 items-center justify-center rounded-xl bg-muted/60 text-muted-foreground">
          <span class="i-ph-article-thin text-lg" />
        </span>
        <h1 class="text-xl font-semibold tracking-tight text-foreground">{{ modalTitle }}</h1>
      </div>
    </header>

    <!-- Form Content -->
    <div class="flex-1 min-h-0 overflow-y-auto custom-scroll">
      <div class="bookmark-form__canvas flex w-full flex-col gap-5 px-6 pb-28 pt-4">
        <!-- 1. URL Input with Inline AI Button -->
        <section class="bookmark-form__section bookmark-form__url-section">
          <label class="bookmark-form__label">链接 / 模板</label>
          <div class="relative group">
            <Input
              v-model="draft.url"
              placeholder="https://example.com 或 {query} 模板"
              class="bookmark-form__control bookmark-form__url-input h-14 font-mono text-base placeholder:text-muted-foreground/50 pr-14"
              auto-focus
            />
            <div class="absolute right-2 top-1/2 -translate-y-1/2">
              <Tooltip v-if="aiEnabled">
                <TooltipTrigger as-child>
                  <Button
                    variant="ghost"
                    size="icon"
                    class="bookmark-form__ai-trigger h-10 w-10 rounded-xl text-primary transition-all"
                    :disabled="!draft.url || isGenerating"
                    @click="askAI()"
                  >
                    <span v-if="isGenerating" class="i-ph-spinner-thin animate-spin text-lg" />
                    <span v-else class="i-ph-star-thin text-lg" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="left">
                  <p v-if="!draft.url">请输入网址以使用 AI</p>
                  <p v-else-if="!canUseAi">{{ aiUnavailableReason }}</p>
                  <p v-else-if="!isUrlAccessible">网址可能无法访问，仍可尝试 AI</p>
                  <p v-else>AI 只预填标题和描述，不会直接保存</p>
                </TooltipContent>
              </Tooltip>
            </div>
          </div>
          <p v-if="formError" class="mt-2 text-[11px] text-destructive">{{ formError }}</p>
        </section>

        <!-- 2. Icon + Title -->
        <section class="bookmark-form__section">
          <div class="flex items-center gap-4">
            <!-- Left: Icon Preview -->
            <div class="shrink-0 flex flex-col items-center gap-2">
              <div class="relative group cursor-pointer" @click="showIconSelector = !showIconSelector">
                <BookmarkIcon
                  :icon="previewIcon"
                  :fallback-text="draft.title || draft.url"
                  :loading="iconLoading"
                  size="custom"
                  custom-size-class="w-20 h-20 rounded-2xl"
                  class="bookmark-form__icon-preview transition-all"
                />
                <div class="absolute inset-0 bg-foreground/50 opacity-0 group-hover:opacity-100 rounded-2xl flex items-center justify-center transition-opacity">
                  <span class="i-ph-pencil-simple-thin text-white text-xl" />
                </div>
              </div>
              <span class="text-xs text-center leading-tight min-h-5 flex items-center" :class="iconLoading ? 'text-amber-500 font-medium animate-pulse' : iconFetchFailed ? 'text-muted-foreground' : 'text-muted-foreground font-medium'">
                {{ iconLoading ? '正在识别站点信息...' : iconFetchFailed ? '识别失败' : '修改图标' }}
              </span>
            </div>

            <!-- Right: Title -->
            <div class="flex-1 min-w-0">
              <div class="relative flex items-center gap-2">
                <Input
                  v-model="draft.title"
                  placeholder="网站标题"
                  class="bookmark-form__control h-12 px-4 text-base font-semibold flex-1"
                  @input="onTitleInput"
                />
                <Button
                  v-if="aiEnabled && hasAIGenerated"
                  variant="ghost"
                  size="icon"
                  class="h-10 w-10 shrink-0 rounded-xl text-muted-foreground hover:text-foreground"
                  @click="undoTitle()"
                >
                  <span class="i-ph-arrow-counter-clockwise-thin text-sm" />
                </Button>
              </div>
            </div>
          </div>

          <!-- Inline Icon Editor (展开式，非弹窗) -->
          <Transition name="fade">
            <div v-if="showIconSelector" class="mt-5 pt-5 border-t border-border/30">
              <IconSelector
                inline
                :modelValue="previewIcon ?? undefined"
                :title="draft.title"
                @update:modelValue="(val) => previewIcon = val"
                @close="showIconSelector = false"
                @confirm="showIconSelector = false"
              />
            </div>
          </Transition>
        </section>

        <!-- 3. Description (独立全宽区块) -->
        <section class="bookmark-form__section">
          <div class="flex items-center justify-between mb-3">
            <label class="bookmark-form__label !mb-0">描述</label>
            <Button
              v-if="aiEnabled && hasAIGenerated"
              variant="ghost"
              size="icon"
              class="h-8 w-8 rounded-lg text-muted-foreground hover:text-foreground"
              @click="undoDesc()"
            >
              <span class="i-ph-arrow-counter-clockwise-thin text-sm" />
            </Button>
          </div>
          <Textarea
            :model-value="draft.desc"
            placeholder="请输入网站简介..."
            class="min-h-[120px] resize-y"
            @update:model-value="(value: string | number) => onDescInput(String(value))"
          />
        </section>

        <!-- 4. Category (独立全宽区块) -->
        <section class="bookmark-form__section">
          <div class="flex items-center justify-between">
            <label class="bookmark-form__label">分类</label>
            <Button
              v-if="aiEnabled"
              variant="ghost"
              size="sm"
              class="bookmark-form__suggest-trigger h-8 text-xs gap-1 px-3 rounded-xl text-primary hover:text-primary"
              :disabled="!draft.url || isSuggestingCategory"
              @click="askCategorySuggestion"
            >
              <span v-if="isSuggestingCategory" class="i-ph-spinner-thin animate-spin" />
              <span v-else class="i-ph-magic-wand-thin" />
              AI 推荐
            </Button>
          </div>

          <Transition name="fade">
            <div v-if="aiEnabled && categorySuggestion" class="bookmark-form__suggestion flex items-center gap-2 px-3 py-1.5 rounded-lg">
              <span class="i-ph-lightbulb-thin text-primary text-base shrink-0" />
              <div class="flex-1 min-w-0">
                <p class="text-[11px] font-medium text-foreground truncate">
                  {{ categorySuggestion.groupName }} / {{ categorySuggestion.subGroupName }}
                </p>
              </div>
              <div class="flex gap-1 shrink-0">
                <Button variant="ghost" size="icon" class="h-6 w-6" @click="applyCategorySuggestion">
                  <span class="i-ph-check-thin text-green-500 text-sm" />
                </Button>
                <Button variant="ghost" size="icon" class="h-6 w-6" @click="dismissCategorySuggestion">
                  <span class="i-ph-x-thin text-muted-foreground text-sm" />
                </Button>
              </div>
            </div>
          </Transition>

          <!-- 平铺展示分类选择 -->
          <CategoryMultiSelect
            v-model="draftLocations"
            inline
          />
        </section>

        <!-- Footer Buttons (sticky at bottom) -->
        <div class="bookmark-form__footer sticky bottom-4 flex items-center justify-between gap-3 rounded-2xl bg-background/90 px-4 py-3 backdrop-blur-sm">
          <div class="flex-1">
            <Button
              v-if="editingId"
              variant="ghost"
              size="sm"
              class="bookmark-form__delete-trigger text-destructive hover:text-destructive px-3 h-9 rounded-xl"
              @click="requestDelete"
            >
              <span class="i-ph-trash-thin mr-1 text-base" />
              删除
            </Button>
          </div>
          <div class="flex items-center gap-2">
            <Button variant="ghost" size="sm" class="h-10 w-24 rounded-xl text-muted-foreground" @click="handleClose">取消</Button>
            <Tooltip v-if="aiEnabled && !editingId && canUseAi">
              <TooltipTrigger as-child>
                <Button variant="outline" size="sm" class="h-10 px-4 rounded-xl bg-background/80" :disabled="isSaving || !draft.url" @click="onAiBackgroundSave">
                  <span v-if="isSaving" class="i-ph-spinner-thin animate-spin mr-1" />
                  <span v-else class="i-ph-star-thin mr-1" />
                  AI 后台保存
                </Button>
              </TooltipTrigger>
              <TooltipContent side="top" class="max-w-[260px] text-xs leading-5">
                <p>{{ aiBackgroundTooltip }}</p>
              </TooltipContent>
            </Tooltip>
            <Button size="sm" class="h-10 w-28 rounded-xl" :disabled="isSaving" @click="onSave">
              <span v-if="isSaving" class="i-ph-spinner-thin animate-spin mr-1" />
              {{ saveButtonLabel }}
            </Button>
          </div>
        </div>
      </div>
    </div>

  </div>
</template>

<style scoped>
.bookmark-form-page {
  --form-surface: hsl(var(--card) / 0.72);
  --form-control-border: hsl(var(--border) / 0.72);
}

.bookmark-form__canvas {
  max-width: none;
}

.bookmark-form__section {
  width: 100%;
  border-radius: 28px;
  background: var(--form-surface);
  padding: 1.5rem;
}

.bookmark-form__url-section {
  padding: 1.25rem 1.5rem;
}

.bookmark-form__label {
  display: inline-flex;
  margin-bottom: 0.75rem;
  font-size: 0.8125rem;
  font-weight: 700;
  color: hsl(var(--muted-foreground));
}

.bookmark-form__control {
  border: 1px solid var(--form-control-border) !important;
  border-radius: 1rem !important;
  background: hsl(var(--background) / 0.72) !important;
  box-shadow: none !important;
  transition: border-color 0.16s ease, background-color 0.16s ease, box-shadow 0.16s ease;
}

.bookmark-form__control:hover {
  border-color: hsl(var(--muted-foreground) / 0.34) !important;
}

.bookmark-form__control:focus,
.bookmark-form__control:focus-visible {
  border-color: hsl(var(--primary) / 0.72) !important;
  box-shadow: 0 0 0 3px hsl(var(--primary) / 0.12) !important;
}

.bookmark-form__url-input {
  letter-spacing: -0.01em;
}

.bookmark-form__icon-preview {
  box-shadow: 0 14px 34px hsl(var(--foreground) / 0.06);
}

.bookmark-form__footer {
  box-shadow: 0 18px 48px hsl(var(--foreground) / 0.08);
}

.bookmark-form__ai-trigger:hover,
.bookmark-form__suggest-trigger:hover {
  background-color: hsl(var(--primary) / 0.1);
}

.bookmark-form__suggest-trigger:active {
  background-color: hsl(var(--primary) / 0.15);
}

.bookmark-form__suggestion {
  background-color: hsl(var(--primary) / 0.05);
}

.bookmark-form__delete-trigger:hover {
  background-color: hsl(var(--destructive) / 0.1);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(4px);
}

.custom-scroll::-webkit-scrollbar {
  width: 4px;
}
.custom-scroll::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scroll::-webkit-scrollbar-thumb {
  background-color: hsl(var(--muted-foreground) / 0.3);
  border-radius: var(--radius-sm);
}
.custom-scroll::-webkit-scrollbar-thumb:hover {
  background-color: hsl(var(--muted-foreground) / 0.5);
}
</style>

// src/components/bookmarks/BookmarkFormDialog.tsx
import { cn } from '@/lib/utils'
import { useBookmarkForm } from '@/hooks/useBookmarkForm'
import { BookmarkIcon } from '@/components/BookmarkIcon'
import { IconSelector } from '@/components/IconSelector'
import { CategoryMultiSelect } from '@/components/CategoryMultiSelect'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import { BookmarkTooltip } from './_BookmarkTooltip'
import {
  ArrowLeft,
  FileText,
  Loader2,
  Sparkles,
  Pencil,
  RotateCcw,
  Wand2,
  Lightbulb,
  Check,
  X,
  Trash2
} from 'lucide-react'

/**
 * BookmarkFormDialog（React 版）
 * --------------------------------------------------------------------------
 * 新建/编辑书签全屏表单页：URL + 内联 AI 取标题/描述、图标预览 + 内联 IconSelector、
 * 标题（AI 撤销）、描述（AI 撤销）、分类（AI 推荐 + CategoryMultiSelect）、底部保存/取消/
 * AI 后台保存/删除。等价旧版 Vue BookmarkFormDialog.vue。
 * 状态来自第 2 阶段 useBookmarkForm（暴露 set/patchDraft 替代 v-model）。
 * i-ph 图标 → lucide-react；Input/Textarea/Button/BookmarkIcon/IconSelector/CategoryMultiSelect 复用。
 *
 * 注：旧版模板用到的 isUrlAccessible / isCheckingUrl / aiBackgroundTooltip 在 React hook
 * 中未导出（以本地 hook 契约为准），此处用静态文案兜底，不改变交互逻辑。无埋点。
 */
export interface BookmarkFormDialogProps {
  onClose: () => void
}

const AI_BACKGROUND_TOOLTIP = '先保存书签，再在后台用 AI 补全标题与描述，无需等待。'

export function BookmarkFormDialog({ onClose }: BookmarkFormDialogProps) {
  const {
    modalTitle,
    draft,
    draftLocations,
    previewIcon,
    showIconSelector,
    formError,
    isSaving,
    iconLoading,
    iconFetchFailed,
    saveButtonLabel,
    aiEnabled,
    canUseAi,
    aiUnavailableReason,
    hasAIGenerated,
    isGenerating,
    isSuggestingCategory,
    categorySuggestion,
    editingId,
    set,
    patchDraft,
    handleSave,
    askAI,
    undoTitle,
    undoDesc,
    onTitleInput,
    onDescInput,
    askCategorySuggestion,
    applyCategorySuggestion,
    dismissCategorySuggestion,
    requestDelete
  } = useBookmarkForm()

  const onSave = async () => {
    await handleSave()
  }
  const onAiBackgroundSave = async () => {
    await handleSave({ forceAi: true, background: true })
  }

  return (
    <div className="bookmark-form-page flex flex-col h-full bg-background relative z-10">
      {/* Header */}
      <header className="shrink-0 z-30 flex items-center gap-4 px-6 pt-5 pb-3">
        <Button
          variant="outline"
          size="icon"
          className="h-10 w-10 shrink-0 rounded-xl bg-background/80"
          onClick={onClose}
        >
          <ArrowLeft className="size-[18px]" />
        </Button>
        <div className="flex items-center gap-3">
          <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-muted/60 text-muted-foreground">
            <FileText className="size-[18px]" />
          </span>
          <h1 className="text-xl font-semibold tracking-tight text-foreground">{modalTitle}</h1>
        </div>
      </header>

      {/* Form Content */}
      <div className="flex-1 min-h-0 overflow-y-auto custom-scroll">
        <div className="bookmark-form__canvas flex w-full flex-col gap-5 px-6 pb-28 pt-4">
          {/* 1. URL Input with Inline AI Button */}
          <section className="bookmark-form__section bookmark-form__url-section">
            <label className="bookmark-form__label">链接 / 模板</label>
            <div className="relative group">
              <Input
                value={draft.url}
                onChange={(e) => patchDraft({ url: e.target.value })}
                placeholder="https://example.com 或 {query} 模板"
                className="bookmark-form__control bookmark-form__url-input h-14 font-mono text-base placeholder:text-muted-foreground/50 pr-14"
                autoFocus
              />
              {aiEnabled && (
                <div className="absolute right-2 top-1/2 -translate-y-1/2">
                  <BookmarkTooltip
                    side="left"
                    content={
                      <p>
                        {!draft.url
                          ? '请输入网址以使用 AI'
                          : !canUseAi
                            ? aiUnavailableReason
                            : 'AI 只预填标题和描述，不会直接保存'}
                      </p>
                    }
                  >
                    <Button
                      variant="ghost"
                      size="icon"
                      className="bookmark-form__ai-trigger h-10 w-10 rounded-xl text-primary transition-all"
                      disabled={!draft.url || isGenerating}
                      onClick={() => askAI()}
                    >
                      {isGenerating ? (
                        <Loader2 className="size-[18px] animate-spin" />
                      ) : (
                        <Sparkles className="size-[18px]" />
                      )}
                    </Button>
                  </BookmarkTooltip>
                </div>
              )}
            </div>
            {formError && <p className="mt-2 text-[11px] text-destructive">{formError}</p>}
          </section>

          {/* 2. Icon + Title */}
          <section className="bookmark-form__section">
            <div className="flex items-center gap-4">
              {/* Left: Icon Preview */}
              <div className="shrink-0 flex flex-col items-center gap-2">
                <div
                  className="relative group cursor-pointer"
                  onClick={() => set({ showIconSelector: !showIconSelector })}
                >
                  <BookmarkIcon
                    icon={previewIcon}
                    fallbackText={draft.title || draft.url}
                    loading={iconLoading}
                    size="custom"
                    customSizeClass="w-20 h-20 rounded-2xl"
                    className="bookmark-form__icon-preview transition-all"
                  />
                  <div className="absolute inset-0 bg-foreground/50 opacity-0 group-hover:opacity-100 rounded-2xl flex items-center justify-center transition-opacity">
                    <Pencil className="text-white size-5" />
                  </div>
                </div>
                <span
                  className={cn(
                    'text-xs text-center leading-tight min-h-5 flex items-center',
                    iconLoading
                      ? 'text-amber-500 font-medium animate-pulse'
                      : iconFetchFailed
                        ? 'text-muted-foreground'
                        : 'text-muted-foreground font-medium'
                  )}
                >
                  {iconLoading ? '正在识别站点信息...' : iconFetchFailed ? '识别失败' : '修改图标'}
                </span>
              </div>

              {/* Right: Title */}
              <div className="flex-1 min-w-0">
                <div className="relative flex items-center gap-2">
                  <Input
                    value={draft.title}
                    onChange={(e) => {
                      patchDraft({ title: e.target.value })
                      onTitleInput()
                    }}
                    placeholder="网站标题"
                    className="bookmark-form__control h-12 px-4 text-base font-semibold flex-1"
                  />
                  {aiEnabled && hasAIGenerated && (
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-10 w-10 shrink-0 rounded-xl text-muted-foreground hover:text-foreground"
                      onClick={() => undoTitle()}
                    >
                      <RotateCcw className="size-3.5" />
                    </Button>
                  )}
                </div>
              </div>
            </div>

            {/* Inline Icon Editor */}
            {showIconSelector && (
              <div className="mt-5 pt-5 border-t border-border/30">
                <IconSelector
                  inline
                  value={previewIcon ?? undefined}
                  title={draft.title}
                  onChange={(val) => set({ previewIcon: val })}
                  onClose={() => set({ showIconSelector: false })}
                  onConfirm={() => set({ showIconSelector: false })}
                />
              </div>
            )}
          </section>

          {/* 3. Description */}
          <section className="bookmark-form__section">
            <div className="flex items-center justify-between mb-3">
              <label className="bookmark-form__label !mb-0">描述</label>
              {aiEnabled && hasAIGenerated && (
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 rounded-lg text-muted-foreground hover:text-foreground"
                  onClick={() => undoDesc()}
                >
                  <RotateCcw className="size-3.5" />
                </Button>
              )}
            </div>
            <Textarea
              value={draft.desc}
              onChange={(e) => onDescInput(e.target.value)}
              placeholder="请输入网站简介..."
              className="min-h-[120px] resize-y"
            />
          </section>

          {/* 4. Category */}
          <section className="bookmark-form__section">
            <div className="flex items-center justify-between">
              <label className="bookmark-form__label">分类</label>
              {aiEnabled && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="bookmark-form__suggest-trigger h-8 text-xs gap-1 px-3 rounded-xl text-primary hover:text-primary"
                  disabled={!draft.url || isSuggestingCategory}
                  onClick={() => askCategorySuggestion()}
                >
                  {isSuggestingCategory ? (
                    <Loader2 className="size-3.5 animate-spin" />
                  ) : (
                    <Wand2 className="size-3.5" />
                  )}
                  AI 推荐
                </Button>
              )}
            </div>

            {aiEnabled && categorySuggestion && (
              <div className="bookmark-form__suggestion flex items-center gap-2 px-3 py-1.5 rounded-lg">
                <Lightbulb className="text-primary size-4 shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-medium text-foreground truncate">
                    {categorySuggestion.groupName} / {categorySuggestion.subGroupName}
                  </p>
                </div>
                <div className="flex gap-1 shrink-0">
                  <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => applyCategorySuggestion()}>
                    <Check className="text-green-500 size-3.5" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => dismissCategorySuggestion()}>
                    <X className="text-muted-foreground size-3.5" />
                  </Button>
                </div>
              </div>
            )}

            <CategoryMultiSelect
              inline
              value={draftLocations}
              onChange={(val) => set({ draftLocations: val })}
            />
          </section>

          {/* Footer Buttons */}
          <div className="bookmark-form__footer sticky bottom-4 flex items-center justify-between gap-3 rounded-2xl bg-background/90 px-4 py-3 backdrop-blur-sm">
            <div className="flex-1">
              {editingId && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="bookmark-form__delete-trigger text-destructive hover:text-destructive px-3 h-9 rounded-xl"
                  onClick={() => requestDelete()}
                >
                  <Trash2 className="size-4 mr-1" />
                  删除
                </Button>
              )}
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                className="h-10 w-24 rounded-xl text-muted-foreground"
                onClick={onClose}
              >
                取消
              </Button>
              {aiEnabled && !editingId && canUseAi && (
                <BookmarkTooltip side="top" content={<p className="max-w-[260px] text-xs leading-5">{AI_BACKGROUND_TOOLTIP}</p>}>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-10 px-4 rounded-xl bg-background/80"
                    disabled={isSaving || !draft.url}
                    onClick={onAiBackgroundSave}
                  >
                    {isSaving ? (
                      <Loader2 className="size-3.5 animate-spin mr-1" />
                    ) : (
                      <Sparkles className="size-3.5 mr-1" />
                    )}
                    AI 后台保存
                  </Button>
                </BookmarkTooltip>
              )}
              <Button size="sm" className="h-10 w-28 rounded-xl" disabled={isSaving} onClick={onSave}>
                {isSaving && <Loader2 className="size-3.5 animate-spin mr-1" />}
                {saveButtonLabel}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default BookmarkFormDialog
