// src/components/bookmarks/BookmarksGrid.tsx
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import {
  DndContext,
  closestCenter,
  PointerSensor,
  KeyboardSensor,
  useSensor,
  useSensors,
  type DragEndEvent
} from '@dnd-kit/core'
import {
  SortableContext,
  useSortable,
  rectSortingStrategy,
  sortableKeyboardCoordinates
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { Plus, Trash2 } from 'lucide-react'
import type { Bookmark } from '@/types/bookmark'
import { BookmarkCard } from '@/components/BookmarkCard'
import { Button } from '@/components/ui/button'
import { useUIManager } from '@/hooks/useUIManager'
import { BookmarkTooltip } from './_BookmarkTooltip'
import './bookmarks.css'

/**
 * BookmarksGrid（React 版）
 * --------------------------------------------------------------------------
 * 书签网格视图：@dnd-kit 拖拽排序（替 vuedraggable，emit fromId/toId）、添加卡片、
 * 回收站清空确认 + 成功 Toast（带复制 URL 列表）、highlightedId 居中滚动。
 * 等价旧版 Vue BookmarksGrid.vue。i-ph 图标 → lucide-react；BookmarkCard 复用。
 * 清空成功反馈用 useUIManager.showToast（替旧版 ResultToast）。无埋点。
 */
export interface BookmarksGridProps {
  bookmarks: Bookmark[]
  selectedIndex: number
  isTrashActive: boolean
  setGridRef?: (el: HTMLElement | null) => void
  columns?: number
  hideAddCard?: boolean
  showCommandHints?: boolean
  hintKeyById?: Record<string, string>
  showEdit?: boolean
  showDelete?: boolean
  showLocate?: boolean
  highlightedId?: string | null
  readonly?: boolean
  selectionVariant?: 'default' | 'search'
  /** 顶部插槽（如引导横幅），等价旧版 #header slot */
  header?: ReactNode
  onRemove?: (bookmark: Bookmark) => void
  onEdit?: (bookmark: Bookmark, el?: HTMLElement) => void
  onOpen?: (bookmark: Bookmark) => void
  onContextMenu?: (event: React.MouseEvent, bookmark: Bookmark) => void
  onLocate?: (bookmark: Bookmark) => void
  onAdd?: (el?: HTMLElement) => void
  onEmptyTrash?: () => void
  onReorder?: (payload: { fromId: string; toId: string }) => void
}

const isUTools = typeof window !== 'undefined' && !!(window as unknown as { utools?: unknown }).utools
const ADD_BUTTON_HEIGHT = isUTools ? '60px' : '66px'
const DURATION = 300

interface SortableCardProps {
  bookmark: Bookmark
  index: number
  disabled: boolean
  selected: boolean
  showHint?: boolean
  hintKey?: string
  readonly?: boolean
  showEdit?: boolean
  showDelete?: boolean
  showLocate?: boolean
  highlighted: boolean
  selectionVariant?: 'default' | 'search'
  columns?: number
  onRemove?: (bookmark: Bookmark) => void
  onEdit?: (bookmark: Bookmark, el?: HTMLElement) => void
  onOpen?: (bookmark: Bookmark) => void
  onLocate?: (bookmark: Bookmark) => void
  onContextMenu?: (event: React.MouseEvent, bookmark: Bookmark) => void
}

function SortableCard({
  bookmark,
  index,
  disabled,
  selected,
  showHint,
  hintKey,
  readonly,
  showEdit,
  showDelete,
  showLocate,
  highlighted,
  selectionVariant,
  columns,
  onRemove,
  onEdit,
  onOpen,
  onLocate,
  onContextMenu
}: SortableCardProps) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: bookmark.id,
    disabled
  })

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.4 : undefined,
    zIndex: isDragging ? 100 : undefined
  }

  return (
    <div
      ref={setNodeRef}
      style={style}
      data-bookmark-index={index}
      data-bookmark-id={bookmark.id}
      className="bookmark-card-wrapper"
      {...attributes}
      {...listeners}
    >
      <BookmarkCard
        bookmark={bookmark}
        selected={selected}
        showHint={showHint}
        hintKey={hintKey}
        readonly={readonly}
        showEdit={showEdit}
        showDelete={showDelete}
        showLocate={showLocate}
        highlighted={highlighted}
        selectionVariant={selectionVariant}
        index={index}
        gridColumns={columns}
        onRemove={onRemove}
        onEdit={onEdit}
        onOpen={onOpen}
        onLocate={onLocate}
        onContextMenu={(e) => onContextMenu?.(e, bookmark)}
      />
    </div>
  )
}

export function BookmarksGrid({
  bookmarks,
  selectedIndex,
  isTrashActive,
  setGridRef,
  columns,
  hideAddCard,
  showCommandHints,
  hintKeyById,
  showEdit,
  showDelete,
  showLocate,
  highlightedId,
  readonly,
  selectionVariant,
  header,
  onRemove,
  onEdit,
  onOpen,
  onContextMenu,
  onLocate,
  onAdd,
  onEmptyTrash,
  onReorder
}: BookmarksGridProps) {
  const showToast = useUIManager((s) => s.showToast)
  const sectionRef = useRef<HTMLElement | null>(null)

  // 本地顺序（拖拽中平滑），props 变化时同步（等价旧版 localBookmarks + watch）
  const [localBookmarks, setLocalBookmarks] = useState<Bookmark[]>(bookmarks)
  useEffect(() => {
    setLocalBookmarks(bookmarks)
  }, [bookmarks])

  const [emptyTrashConfirmOpen, setEmptyTrashConfirmOpen] = useState(false)

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
    useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates })
  )

  const cols = columns && columns >= 2 && columns <= 5 ? columns : 4
  const gridStyle: React.CSSProperties = { gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` }

  const itemIds = useMemo(() => localBookmarks.map((b) => b.id), [localBookmarks])

  const handleDragEnd = (event: DragEndEvent) => {
    if (readonly) return
    const { active, over } = event
    if (!over || active.id === over.id) return
    const fromId = String(active.id)
    const toId = String(over.id)
    // 本地立即重排，保证视觉连续；父级据 fromId/toId 重排 store 后回传 props 再同步
    setLocalBookmarks((prev) => {
      const fromIdx = prev.findIndex((b) => b.id === fromId)
      const toIdx = prev.findIndex((b) => b.id === toId)
      if (fromIdx === -1 || toIdx === -1) return prev
      const next = [...prev]
      const [moved] = next.splice(fromIdx, 1)
      next.splice(toIdx, 0, moved)
      return next
    })
    onReorder?.({ fromId, toId })
  }

  // highlightedId 居中滚动（等价旧版 watch highlightedId）
  useEffect(() => {
    if (!highlightedId) return
    requestAnimationFrame(() => {
      const item = document.querySelector(`[data-bookmark-id="${highlightedId}"]`) as HTMLElement | null
      if (!item) return
      let scroller = item.parentElement
      while (scroller && scroller.scrollHeight <= scroller.clientHeight) scroller = scroller.parentElement
      if (!scroller) return
      const target = item.offsetTop - scroller.clientHeight / 2 + item.clientHeight / 2
      const start = scroller.scrollTop
      const delta = Math.max(0, target) - start
      if (Math.abs(delta) < 1) {
        scroller.scrollTop = Math.max(0, target)
        return
      }
      const t0 = performance.now()
      const tick = (now: number) => {
        const t = Math.min((now - t0) / DURATION, 1)
        scroller!.scrollTop = start + delta * (1 - Math.pow(1 - t, 3))
        if (t < 1) requestAnimationFrame(tick)
      }
      requestAnimationFrame(tick)
    })
  }, [highlightedId])

  const copyText = async (text: string) => {
    try {
      if (!navigator.clipboard) {
        showToast({ title: '当前环境不支持剪贴板复制', variant: 'warning' })
        return
      }
      await navigator.clipboard.writeText(text)
      showToast({ title: '已复制到剪贴板', variant: 'success' })
    } catch {
      showToast({ title: '复制失败，请检查权限后重试', variant: 'error' })
    }
  }

  const confirmEmptyTrash = () => {
    const urls = bookmarks.map((b) => b.url).filter(Boolean).join('\n')
    const count = bookmarks.length
    onEmptyTrash?.()
    setEmptyTrashConfirmOpen(false)
    showToast({
      title: '回收站已清空',
      description: count > 0 ? `已永久删除 ${count} 条书签` : undefined,
      variant: 'success',
      actionLabel: urls ? '复制URL列表' : undefined,
      onAction: urls ? () => copyText(urls) : undefined
    })
  }

  return (
    <section
      ref={(el) => {
        sectionRef.current = el
        setGridRef?.(el)
      }}
      className="flex-1"
    >
      {header}

      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
        <SortableContext items={itemIds} strategy={rectSortingStrategy}>
          <div className="grid gap-4 content-start pt-2" style={gridStyle}>
            {localBookmarks.map((bookmark, index) => (
              <SortableCard
                key={bookmark.id}
                bookmark={bookmark}
                index={index}
                disabled={!!readonly}
                selected={selectedIndex === index}
                showHint={showCommandHints}
                hintKey={hintKeyById?.[bookmark.id]}
                readonly={readonly}
                showEdit={showEdit}
                showDelete={showDelete}
                showLocate={showLocate}
                highlighted={highlightedId === bookmark.id}
                selectionVariant={selectionVariant}
                columns={columns}
                onRemove={onRemove}
                onEdit={onEdit}
                onOpen={onOpen}
                onLocate={onLocate}
                onContextMenu={onContextMenu}
              />
            ))}

            {/* 添加卡片 */}
            {!isTrashActive && !hideAddCard && !readonly && (
              <BookmarkTooltip content={<p>添加书签</p>}>
                <Button
                  variant="outline"
                  className="bookmark-add-card group relative flex flex-row items-center justify-center gap-2 rounded-xl border-dashed py-3 px-4 text-muted-foreground hover:border-primary hover:text-primary transition-colors cursor-pointer w-full bg-transparent"
                  style={{ height: ADD_BUTTON_HEIGHT }}
                  onClick={(e) => onAdd?.(e.currentTarget)}
                >
                  <div className="group-hover:scale-110 transition-transform">
                    <Plus className="w-7 h-7" />
                  </div>
                </Button>
              </BookmarkTooltip>
            )}
          </div>
        </SortableContext>
      </DndContext>

      {isTrashActive && bookmarks.length > 0 && (
        <div className="flex justify-center py-8">
          <Button variant="destructive" onClick={() => setEmptyTrashConfirmOpen(true)}>
            <Trash2 className="size-4 mr-2" />
            清空回收站
          </Button>
        </div>
      )}

      {/* 清空回收站确认 */}
      {emptyTrashConfirmOpen && (
        <div
          className="fixed inset-0 z-[2100] flex items-center justify-center bg-black/40 backdrop-blur-sm"
          role="presentation"
        >
          <div
            className="w-full sm:max-w-md mx-4 p-4 rounded-lg bg-card border border-border shadow-lg"
            role="dialog"
            aria-modal="true"
          >
            <h2 className="text-lg font-semibold">清空回收站？</h2>
            <p className="text-sm text-muted-foreground mt-1.5">
              此操作不可恢复，将永久删除回收站内 {bookmarks.length} 条书签。
            </p>
            <div className="flex justify-end gap-3 pt-4">
              <Button variant="ghost" onClick={() => setEmptyTrashConfirmOpen(false)}>
                取消
              </Button>
              <Button variant="destructive" autoFocus onClick={confirmEmptyTrash}>
                确认清空
              </Button>
            </div>
          </div>
        </div>
      )}
    </section>
  )
}

export default BookmarksGrid

// src/components/bookmarks/BookmarksGrid.vue
<script setup lang="ts">
import { computed, ref, watch, nextTick } from 'vue'
import type { Bookmark } from '@/types/bookmark'
import BookmarkCard from '@/components/BookmarkCard.vue'
import { Button } from '@/components/ui/button'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import ResultToast from '@/components/ResultToast.vue'
import { notify } from '@/lib/notify'
import { Plus } from 'lucide-vue-next'
import draggable from 'vuedraggable'

const props = defineProps<{
  bookmarks: Bookmark[]
  selectedIndex: number
  isTrashActive: boolean
  setGridRef?: (el: HTMLElement | null) => void
  columns?: number
  hideAddCard?: boolean
  showCommandHints?: boolean
  hintKeyById?: Record<string, string>
  readonly?: boolean
}>()

const emit = defineEmits<{
  (e: 'remove', bookmark: Bookmark): void
  (e: 'edit', bookmark: Bookmark, el?: HTMLElement): void
  (e: 'open', bookmark: Bookmark): void
  (e: 'contextmenu', event: MouseEvent, bookmark: Bookmark): void
  (e: 'add', el?: HTMLElement): void
  (e: 'emptyTrash'): void
  (e: 'reorder', payload: { fromId: string; toId: string }): void
  (e: 'update:bookmarks', bookmarks: Bookmark[]): void
}>()

// 本地书签列表，用于 v-model
const localBookmarks = computed({
  get: () => props.bookmarks,
  set: (val) => emit('update:bookmarks', val)
})

// vuedraggable change 事件处理
const handleDragChange = (evt: { moved?: { oldIndex: number; newIndex: number } }) => {
  if (!evt.moved || props.readonly) return
  const { oldIndex, newIndex } = evt.moved
  if (oldIndex === newIndex) return
  
  const fromId = props.bookmarks[oldIndex]?.id
  const toId = props.bookmarks[newIndex]?.id
  if (fromId && toId) {
    emit('reorder', { fromId, toId })
  }
}

const gridStyle = computed(() => {
  const cols = props.columns && props.columns >= 2 && props.columns <= 5 ? props.columns : 4
  return { gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` }
})

const emptyTrashConfirmOpen = ref(false)
const emptyToastOpen = ref(false)
const emptyToastTitle = ref('')
const emptyToastDesc = ref<string | undefined>(undefined)
const confirmEmptyTrashButtonRef = ref<HTMLElement | null>(null)
let emptyToastUrls = ''

const copyText = async (text: string) => {
  try {
    if (!navigator.clipboard) {
      notify('当前环境不支持剪贴板复制')
      return
    }
    await navigator.clipboard.writeText(text)
    notify('已复制到剪贴板')
  } catch {
    notify('复制失败，请检查权限后重试')
  }
}

const requestEmptyTrash = () => {
  emptyTrashConfirmOpen.value = true
}

// 当清空回收站确认对话框打开时，聚焦到确认清空按钮
watch(emptyTrashConfirmOpen, (isOpen) => {
  if (isOpen) {
    nextTick(() => {
      // 查找确认清空按钮并聚焦
      const button = confirmEmptyTrashButtonRef.value as HTMLElement | null
      if (button) {
        button.focus()
      } else {
        // 备用方案：通过查询选择器查找
        const dialog = document.querySelector('[role="dialog"]')
        const confirmBtn = dialog?.querySelector('button[class*="destructive"]') as HTMLElement
        confirmBtn?.focus()
      }
    })
  }
})

const confirmEmptyTrash = () => {
  emptyToastUrls = props.bookmarks.map(b => b.url).filter(Boolean).join('\n')
  const count = props.bookmarks.length
  emit('emptyTrash')
  emptyTrashConfirmOpen.value = false

  emptyToastTitle.value = '回收站已清空'
  emptyToastDesc.value = count > 0 ? `已永久删除 ${count} 条书签` : undefined
  emptyToastOpen.value = true
}
</script>

<template>
  <section
    :ref="setGridRef"
    class="flex-1"
  >
    <draggable
      v-model="localBookmarks"
      item-key="id"
      :animation="150"
      ghost-class="bookmark-drag-ghost"
      chosen-class="bookmark-drag-chosen"
      drag-class="bookmark-drag-active"
      class="grid gap-4 content-start"
      :style="gridStyle"
      :disabled="readonly"
      @change="handleDragChange"
    >
      <template #item="{ element: bookmark, index }">
        <div
          :data-bookmark-index="index"
          class="bookmark-card-wrapper"
        >
          <BookmarkCard
            :bookmark="bookmark"
            :selected="selectedIndex === index"
            :show-hint="showCommandHints"
            :hint-key="hintKeyById?.[bookmark.id]"
            @remove="emit('remove', bookmark)"
            @edit="(b, el) => emit('edit', b, el)"
            @open="emit('open', bookmark)"
            @contextmenu="(e) => emit('contextmenu', e, bookmark)"
          />
        </div>
      </template>
      <template #footer>
        <div v-if="!isTrashActive && !hideAddCard && !readonly">
          <Tooltip>
            <TooltipTrigger as-child>
              <Button
                variant="outline"
                class="group relative flex flex-row items-center justify-center gap-2 rounded-xl border-dashed py-2.5 text-muted-foreground hover:border-primary hover:text-primary hover:bg-muted/30 transition-colors cursor-pointer min-h-[60px] w-full"
                @click="(e: MouseEvent) => emit('add', e.currentTarget as HTMLElement)"
              >
                <div class="group-hover:scale-110 transition-transform">
                  <Plus class="w-7 h-7" />
                </div>
              </Button>
            </TooltipTrigger>
            <TooltipContent><p>添加书签</p></TooltipContent>
          </Tooltip>
        </div>
      </template>
    </draggable>

    <div v-if="isTrashActive && bookmarks.length > 0" class="flex justify-center py-8">
      <Button variant="destructive" @click="requestEmptyTrash">
        <span class="i-mdi-delete-empty mr-2" />
        清空回收站
      </Button>
    </div>

    <Dialog :open="emptyTrashConfirmOpen" @update:open="v => (emptyTrashConfirmOpen = v)">
      <DialogContent class="sm:max-w-md" @pointer-down-outside.prevent @interact-outside.prevent>
        <DialogHeader>
          <DialogTitle>清空回收站？</DialogTitle>
          <DialogDescription>此操作不可恢复，将永久删除回收站内 {{ bookmarks.length }} 条书签。</DialogDescription>
        </DialogHeader>
        <DialogFooter class="gap-3">
          <Button variant="ghost" @click="emptyTrashConfirmOpen = false">取消</Button>
          <Button ref="confirmEmptyTrashButtonRef" variant="destructive" @click="confirmEmptyTrash">确认清空</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>

    <ResultToast
      :open="emptyToastOpen"
      variant="success"
      :title="emptyToastTitle"
      :description="emptyToastDesc"
      :action-label="emptyToastUrls ? '复制URL列表' : undefined"
      @close="emptyToastOpen = false"
      @action="copyText(emptyToastUrls)"
    />
  </section>
</template>

<style scoped>
/* 拖拽占位 Ghost */
.bookmark-drag-ghost {
  opacity: 0.4;
  background: hsl(var(--primary) / 0.08);
  border-radius: 12px;
  border: 2px dashed hsl(var(--primary) / 0.4) !important;
}

/* 被选中的卡片 */
.bookmark-drag-chosen {
  opacity: 1;
  transform: scale(1.03) rotate(1deg);
  box-shadow: 0 12px 40px hsl(var(--primary) / 0.2);
  z-index: 100;
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}

/* 拖拽中的卡片 */
.bookmark-drag-active {
  cursor: grabbing !important;
  opacity: 0.95;
}

/* 卡片容器动画 */
.bookmark-card-wrapper {
  transition: transform 0.2s ease;
}
</style>
