// src/components/bookmarks/GroupTabs.tsx
import { useState } from 'react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Search, Settings, MoonStar, Trash2 } from 'lucide-react'
import { BookmarkTooltip } from './_BookmarkTooltip'
import './bookmarks.css'

/**
 * GroupTabs（React 版）
 * --------------------------------------------------------------------------
 * 顶部一级分组标签行 + 右侧操作区（搜索 / 设置 / 深浅模式 / 回收站）。
 * 等价旧版 Vue GroupTabs.vue。i-ph 图标 → lucide-react。
 * 受控 tab + 各类回调。无埋点。
 */
interface GroupTabsSubGroup {
  id: string
  name: string
}
export interface GroupTabsGroup {
  id: string
  name: string
  children: GroupTabsSubGroup[]
}

export interface GroupTabsProps {
  visibleGroups: GroupTabsGroup[]
  activeGroupId: string
  tab: 'bookmarks' | 'settings'
  isUTools: boolean
  isTrashActive: boolean
  searching: boolean
  groupLayout?: 'wrap' | 'scroll'
  onTabChange: (value: 'bookmarks' | 'settings') => void
  onSelectGroup: (id: string) => void
  onSelectTrash: () => void
  onToggleDark: () => void
  onOpenSearch: () => void
  onEditGroup: (id: string) => void
}

const formatName = (name: string) => (name.length > 8 ? `${name.slice(0, 8)}…` : name)

export function GroupTabs({
  visibleGroups,
  activeGroupId,
  tab,
  isTrashActive,
  searching,
  groupLayout,
  onTabChange,
  onSelectGroup,
  onSelectTrash,
  onToggleDark,
  onOpenSearch,
  onEditGroup
}: GroupTabsProps) {
  // 溢出（名称 > 8 字符被截断）→ 才显示 tooltip，等价旧版 overflowMap 逻辑
  const [overflowMap, setOverflowMap] = useState<Record<string, boolean>>({})

  const groupContainerClass =
    groupLayout === 'scroll'
      ? 'flex items-center gap-2 overflow-x-auto no-scrollbar mask-gradient-right whitespace-nowrap'
      : 'flex items-center flex-wrap gap-2'

  const handleGroupMouseEnter = (group: GroupTabsGroup) => {
    setOverflowMap((prev) => ({ ...prev, [group.id]: group.name.length > 8 }))
  }

  return (
    <div className="flex items-center justify-between">
      <div className={groupContainerClass}>
        {visibleGroups.map((group) => (
          <BookmarkTooltip
            key={group.id}
            content={<p>{group.name}</p>}
            disabled={!overflowMap[group.id]}
          >
            <Button
              variant="ghost"
              size="sm"
              className="main-group-tab group-tab-btn rounded-full px-4 h-9 font-normal transition-all border border-transparent"
              data-active={activeGroupId === group.id ? 'true' : undefined}
              onClick={() => onSelectGroup(group.id)}
              onMouseEnter={() => handleGroupMouseEnter(group)}
              onContextMenu={(e) => {
                e.preventDefault()
                onEditGroup(group.id)
              }}
            >
              {formatName(group.name)}
            </Button>
          </BookmarkTooltip>
        ))}
      </div>

      <div className="flex items-center gap-2 shrink-0 ml-4">
        <BookmarkTooltip content={<p className="text-xs">直接输入字符即可搜索</p>}>
          <Button
            variant="outline"
            size="sm"
            className={cn(
              'group-action-btn h-9 rounded-full px-3 flex items-center gap-1',
              searching && 'group-action-btn--searching'
            )}
            onClick={onOpenSearch}
          >
            <Search className="size-4" />
            <span className="text-xs">搜索</span>
          </Button>
        </BookmarkTooltip>

        <div className="h-6 w-px bg-border mx-2" />

        <BookmarkTooltip content={<p>设置</p>}>
          <Button
            variant="ghost"
            size="icon"
            className={cn(
              'w-8 h-8 text-muted-foreground hover:text-foreground',
              tab === 'settings' && 'bg-muted text-foreground'
            )}
            onClick={() => onTabChange('settings')}
            aria-label="设置"
          >
            <Settings className="size-[18px]" />
          </Button>
        </BookmarkTooltip>

        <div className="h-6 w-px bg-border mx-2" />

        <BookmarkTooltip content={<p>切换深浅模式</p>}>
          <Button
            variant="ghost"
            size="icon"
            className="w-7 h-7 text-muted-foreground hover:text-foreground"
            onClick={onToggleDark}
            aria-label="切换深浅模式"
          >
            <MoonStar className="size-[18px]" />
          </Button>
        </BookmarkTooltip>

        <div className="h-6 w-px bg-border mx-2" />

        <BookmarkTooltip content={<p>回收站</p>}>
          <Button
            variant="ghost"
            size="icon"
            className={cn(
              'w-7 h-7 text-muted-foreground hover:text-destructive transition-colors',
              isTrashActive && 'group-action-btn--danger-active text-destructive'
            )}
            onClick={onSelectTrash}
            aria-label="回收站"
          >
            <Trash2 className="size-[18px]" />
          </Button>
        </BookmarkTooltip>
      </div>
    </div>
  )
}

export default GroupTabs

// src/components/bookmarks/GroupTabs.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useTextOverflow } from '@/composables/useTextOverflow'

interface SubGroup {
  id: string
  name: string
}

interface Group {
  id: string
  name: string
  children: SubGroup[]
}

const props = defineProps<{
  visibleGroups: Group[]
  activeGroupId: string
  tab: 'bookmarks' | 'settings'
  isUTools: boolean
  isTrashActive: boolean
  searching: boolean
  groupLayout?: 'wrap' | 'scroll'
}>()

const emit = defineEmits<{
  (e: 'update:tab', value: 'bookmarks' | 'settings'): void
  (e: 'select-group', id: string): void
  (e: 'select-trash'): void
  (e: 'toggle-dark'): void
  (e: 'open-search'): void
}>()

const setTab = (value: 'bookmarks' | 'settings') => emit('update:tab', value)
const formatName = (name: string) => (name.length > 8 ? `${name.slice(0, 8)}…` : name)


const groupContainerClass = computed(() => {
  if (props.groupLayout === 'scroll') {
    return 'flex items-center gap-2 overflow-x-auto no-scrollbar mask-gradient-right whitespace-nowrap'
  }
  return 'flex items-center flex-wrap gap-2'
})

// 溢出检测：名称超过 8 个字符会被截断
const { overflowMap } = useTextOverflow()

// 鼠标进入时检查是否需要显示 tooltip（名称被截断时）
const handleGroupMouseEnter = (group: Group) => {
  // 名称超过 8 个字符会被 formatName 截断
  overflowMap.value[group.id] = group.name.length > 8
}
</script>

<template>
  <div class="flex items-center justify-between">
    <div :class="groupContainerClass">
      <Tooltip v-for="group in visibleGroups" :key="group.id" :disabled="!overflowMap[group.id]">
        <TooltipTrigger as-child>
          <Button
            variant="ghost"
            size="sm"
            class="main-group-tab group-tab-btn rounded-full px-4 h-9 font-normal transition-all border border-transparent"
            :data-active="activeGroupId === group.id ? 'true' : undefined"
            @click="emit('select-group', group.id)"
            @mouseenter="handleGroupMouseEnter(group)"
          >
            {{ formatName(group.name) }}
          </Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>{{ group.name }}</p>
        </TooltipContent>
      </Tooltip>
    </div>

    <div class="flex items-center gap-2 shrink-0 ml-4">
      <Tooltip>
        <TooltipTrigger as-child>
          <Button
            variant="outline"
            size="sm"
            class="group-action-btn h-9 rounded-full px-3 flex items-center gap-1"
            :class="{ 'group-action-btn--searching': searching }"
            @click="emit('open-search')"
          >
            <span class="i-mdi-magnify text-lg" />
            <span class="text-xs">搜索</span>
          </Button>
        </TooltipTrigger>
        <TooltipContent>
          <p class="text-xs">直接输入字符即可搜索</p>
        </TooltipContent>
      </Tooltip>

      <div class="h-6 w-px bg-border mx-2"></div>

      <Tooltip>
        <TooltipTrigger as-child>
          <Button
            variant="ghost"
            size="icon"
            class="w-8 h-8 text-muted-foreground hover:text-foreground"
            :class="{ 'bg-muted text-foreground': tab === 'settings' }"
            @click="setTab('settings')"
            aria-label="设置"
          >
            <span class="i-mdi-cog-outline text-lg" />
          </Button>
        </TooltipTrigger>
        <TooltipContent><p>设置</p></TooltipContent>
      </Tooltip>

      <div class="h-6 w-px bg-border mx-2"></div>

      <Tooltip>
        <TooltipTrigger as-child>
          <Button
            variant="ghost"
            size="icon"
            class="w-7 h-7 text-muted-foreground hover:text-foreground"
            @click="emit('toggle-dark')"
          >
            <span class="i-mdi-theme-light-dark text-lg" />
          </Button>
        </TooltipTrigger>
        <TooltipContent><p>切换深浅模式</p></TooltipContent>
      </Tooltip>

      <div class="h-6 w-px bg-border mx-2"></div>

      <Tooltip>
        <TooltipTrigger as-child>
          <Button
            variant="ghost"
            size="icon"
            class="w-7 h-7 text-muted-foreground hover:text-destructive transition-colors"
            :class="{ 'group-action-btn--danger-active text-destructive': isTrashActive }"
            @click="emit('select-trash')"
          >
            <span class="i-mdi-trash-can-outline text-lg" />
          </Button>
        </TooltipTrigger>
        <TooltipContent><p>回收站</p></TooltipContent>
      </Tooltip>
    </div>
  </div>
</template>

<style scoped>
.group-tab-btn {
  color: hsl(var(--muted-foreground));
  background-color: transparent;
}

.group-tab-btn:hover {
  color: hsl(var(--foreground));
  background-color: hsl(var(--muted) / 0.8);
}

.group-tab-btn[data-active="true"] {
  color: hsl(var(--foreground));
  background-color: hsl(var(--muted));
  border-color: hsl(var(--border));
  box-shadow: 0 1px 2px hsl(var(--foreground) / 0.08);
}

.dark .group-tab-btn:hover {
  color: hsl(var(--accent-foreground));
  background-color: hsl(var(--accent));
}

.dark .group-tab-btn[data-active="true"] {
  color: hsl(var(--accent-foreground));
  background-color: hsl(var(--accent));
  border-color: hsl(var(--primary) / 0.3);
  box-shadow: 0 4px 10px hsl(var(--background) / 0.45);
}

.group-action-btn--searching {
  border-color: hsl(var(--primary));
  color: hsl(var(--primary));
  background-color: hsl(var(--primary) / 0.1);
}

.group-action-btn--danger-active {
  background-color: hsl(var(--destructive) / 0.1);
}
</style>
