// src/components/bookmarks/SubGroupItem.tsx
import { useEffect, useRef } from 'react'
import { cn } from '@/lib/utils'
import { useTextOverflow } from '@/hooks/useTextOverflow'
import { useUIManager } from '@/hooks/useUIManager'
import { BookmarkTooltip } from './_BookmarkTooltip'
import './bookmarks.css'

/**
 * SubGroupItem（React 版）
 * --------------------------------------------------------------------------
 * 侧栏二级分组按钮，支持选中/拖拽悬停态、文字溢出 tooltip、右键编辑父分组。
 * 等价旧版 Vue SubGroupItem.vue。useTextOverflow / useUIManager 来自第 2 阶段 hooks。
 * 无埋点。
 */
export interface SubGroupItemSub {
  id: string
  name: string
  bookmarkIds?: string[]
}

export interface SubGroupItemProps {
  sub: SubGroupItemSub
  isActive: boolean
  isDragOver: boolean
  hasUpdate: boolean
  onSelect: (id: string) => void
  onDragOver?: (event: React.DragEvent) => void
  onDragLeave?: (event: React.DragEvent) => void
  onDrop?: (event: React.DragEvent) => void
  onEditParentGroup?: () => void
}

export function SubGroupItem({
  sub,
  isActive,
  isDragOver,
  hasUpdate,
  onSelect,
  onDragOver,
  onDragLeave,
  onDrop,
  onEditParentGroup
}: SubGroupItemProps) {
  const isTooltipEnabled = useUIManager((s) => s.isTooltipEnabled)
  const { overflowMap, observeOverflow } = useTextOverflow()
  const nameRef = useRef<HTMLDivElement | null>(null)

  // 名称变化时重新检测溢出（等价旧版 watch + onMounted + nextTick）
  useEffect(() => {
    if (nameRef.current) observeOverflow('self', nameRef.current)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sub.name])

  const isTruncated = overflowMap['self'] ?? false

  const handleSelect = (event: React.MouseEvent<HTMLButtonElement>) => {
    onSelect(sub.id)
    event.currentTarget.blur?.()
  }

  return (
    <BookmarkTooltip
      content={<p>{sub.name}</p>}
      disabled={!isTooltipEnabled || !isTruncated}
      side="right"
      offset={8}
    >
      <button
        type="button"
        className={cn(
          'subgroup-btn flex items-center justify-start w-full px-3 py-2 rounded-md text-sm transition-none text-left relative min-w-0 overflow-hidden outline-none disabled:pointer-events-none disabled:opacity-50',
          isActive ? 'subgroup-btn--active' : 'subgroup-btn--idle',
          isDragOver && 'subgroup-btn--drag-over'
        )}
        data-active={isActive ? 'true' : undefined}
        onPointerDown={(e) => e.preventDefault()}
        onMouseDown={(e) => e.preventDefault()}
        onClick={handleSelect}
        onContextMenu={(e) => {
          e.preventDefault()
          onEditParentGroup?.()
        }}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        onDrop={onDrop}
      >
        <div ref={nameRef} className="flex-1 min-w-0 truncate block">
          {sub.name}
        </div>
        {hasUpdate && (
          <span className="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full animate-pulse" />
        )}
      </button>
    </BookmarkTooltip>
  )
}

export default SubGroupItem

// src/components/bookmarks/SubGroupItem.vue
<script setup lang="ts">
import { useTextOverflow } from '@/composables/useTextOverflow'
import { useUIManager } from '@/composables/useUIManager'

const props = defineProps<{
  sub: { id: string; name: string; bookmarkIds?: string[] }
  isActive: boolean
  isDragOver: boolean
  hasUpdate: boolean
}>()

const emit = defineEmits<{
  (e: 'select', id: string): void
  (e: 'dragover', event: DragEvent): void
  (e: 'dragleave', event: DragEvent): void
  (e: 'drop', event: DragEvent): void
}>()

const { isTooltipEnabled } = useUIManager()
const { overflowMap, observeOverflow } = useTextOverflow()

const nameRef = ref<HTMLElement | null>(null)

const refreshOverflow = () => {
  if (!nameRef.value) return
  observeOverflow('self', nameRef.value)
}

watch(() => props.sub.name, () => {
  nextTick(refreshOverflow)
})

onMounted(() => {
  nextTick(refreshOverflow)
})

const isTruncated = computed(() => overflowMap.value['self'] ?? false)

const stateClass = computed(() => ({
  'subgroup-btn--active': props.isActive,
  'subgroup-btn--idle': !props.isActive,
  'subgroup-btn--drag-over': props.isDragOver
}))

const handleSelect = (event: MouseEvent) => {
  emit('select', props.sub.id)
  const target = event.currentTarget as HTMLElement | null
  target?.blur?.()
}
</script>

<template>
  <Tooltip :disabled="!isTooltipEnabled || !isTruncated">
    <TooltipTrigger as-child>
      <button
        type="button"
        class="subgroup-btn flex items-center justify-start w-full px-3 py-2 rounded-md text-sm transition-none text-left relative min-w-0 overflow-hidden outline-none disabled:pointer-events-none disabled:opacity-50"
        :data-active="isActive ? 'true' : undefined"
        :class="stateClass"
        @pointerdown.prevent
        @mousedown.prevent
        @click="handleSelect"
        @dragover="emit('dragover', $event)"
        @dragleave="emit('dragleave', $event)"
        @drop="emit('drop', $event)"
      >
        <div ref="nameRef" class="flex-1 min-w-0 truncate block">
          {{ sub.name }}
        </div>
        <span v-if="hasUpdate" class="absolute -top-1 -right-1 w-2 h-2 bg-red-500 rounded-full animate-pulse" />
      </button>
    </TooltipTrigger>
    <TooltipContent side="right" :side-offset="8" align="center">
      <p>{{ sub.name }}</p>
    </TooltipContent>
  </Tooltip>
</template>

<style scoped>
.subgroup-btn {
  border-left: 2px solid transparent;
  color: hsl(var(--muted-foreground));
  background-color: transparent;
}

.subgroup-btn--idle:hover {
  color: hsl(var(--foreground));
  background-color: hsl(var(--muted) / 0.8);
}

.subgroup-btn--active {
  color: hsl(var(--foreground));
  font-weight: 500;
  border-left-color: hsl(var(--primary));
  background-color: hsl(var(--muted));
}

.dark .subgroup-btn--idle:hover {
  color: hsl(var(--accent-foreground));
  background-color: hsl(var(--accent));
}

.dark .subgroup-btn--active {
  color: hsl(var(--accent-foreground));
  background-color: hsl(var(--accent));
}

.subgroup-btn--drag-over {
  color: hsl(var(--foreground));
  background-color: hsl(var(--primary) / 0.1);
  box-shadow: inset 0 0 0 2px hsl(var(--primary) / 0.55);
}

.dark .subgroup-btn--drag-over {
  color: hsl(var(--primary));
}

.subgroup-btn:focus,
.subgroup-btn:focus-visible,
.subgroup-btn:focus-within,
.subgroup-btn:active {
  outline: none !important;
  box-shadow: none !important;
  --tw-ring-offset-shadow: 0 0 #0000 !important;
  --tw-ring-shadow: 0 0 #0000 !important;
  --tw-ring-color: transparent !important;
}
</style>
