// src/components/bookmarks/SubGroupSidebar.tsx
import { useMemo } from 'react'
import { cn } from '@/lib/utils'
import { Trash2 } from 'lucide-react'
import { useBookmarkStore, TRASH_GROUP_ID } from '@/stores/bookmark'
import './bookmarks.css'

/**
 * SubGroupSidebar（React 版）
 * --------------------------------------------------------------------------
 * 大纲式分组/子分组导航侧栏（含书签计数 + 回收站入口）。可外部传入 groups，
 * 否则从 store 派生。等价旧版 Vue SubGroupSidebar.vue。
 * 旧版 store.selectGroup → React store.setActiveGroup。无埋点。
 */
export interface OutlineSubGroup {
  subGroupId: string
  subGroupName: string
  bookmarkCount: number
  anchorId: string
}
export interface OutlineGroup {
  groupId: string
  groupName: string
  bookmarkCount: number
  children: OutlineSubGroup[]
}

export interface SubGroupSidebarProps {
  groups?: OutlineGroup[]
  activeAnchorId?: string
  onScrollTo: (anchorId: string) => void
  onEditGroup?: (groupId: string) => void
  onFocusSearch?: () => void
}

export function SubGroupSidebar({
  groups,
  activeAnchorId,
  onScrollTo,
  onFocusSearch
}: SubGroupSidebarProps) {
  const storeGroups = useBookmarkStore((s) => s.groups)
  const activeGroupId = useBookmarkStore((s) => s.activeGroupId)
  const setActiveGroup = useBookmarkStore((s) => s.setActiveGroup)

  // 未传 groups 时从 store 计算（含子分组），等价旧版 computed
  const outlineGroups = useMemo<OutlineGroup[]>(() => {
    if (groups?.length) return groups

    return storeGroups
      .filter((g) => g.id !== TRASH_GROUP_ID)
      .map((group) => {
        const children = group.children
          .filter((sub) => (sub.bookmarkIds?.length || 0) > 0)
          .map((sub) => ({
            subGroupId: sub.id,
            subGroupName: sub.name,
            bookmarkCount: sub.bookmarkIds?.length || 0,
            anchorId: `section-${group.id}-${sub.id}`
          }))
        const bookmarkCount = children.reduce((sum, sub) => sum + sub.bookmarkCount, 0)
        return { groupId: group.id, groupName: group.name, bookmarkCount, children }
      })
      .filter((g) => g.bookmarkCount > 0)
  }, [groups, storeGroups])

  const isSubGroupActive = (anchorId: string) => {
    if (!activeAnchorId) return false
    return activeAnchorId === anchorId || anchorId.startsWith(`${activeAnchorId}-`)
  }

  const handleSubGroupClick = (anchorId: string) => {
    onScrollTo(anchorId)
    onFocusSearch?.()
  }

  return (
    <aside className="bm-no-scrollbar shrink-0 w-36 flex flex-col overflow-y-auto py-2 px-2 gap-1">
      <div className="flex flex-col gap-2">
        {outlineGroups.map((group) => (
          <div key={group.groupId} className="flex flex-col gap-0.5">
            <div className="px-2 py-1 text-[10px] font-semibold text-muted-foreground/50 uppercase tracking-wider">
              {group.groupName}
            </div>
            {group.children.map((sub) => (
              <button
                key={sub.subGroupId}
                type="button"
                className={cn(
                  'group-nav-item relative flex items-center gap-2 pl-5 pr-2 py-1 rounded-md text-left text-xs transition-colors duration-120',
                  isSubGroupActive(sub.anchorId) ? 'group-nav-item--active' : 'group-nav-item--idle'
                )}
                onClick={() => handleSubGroupClick(sub.anchorId)}
              >
                <span className="truncate flex-1">{sub.subGroupName}</span>
                {sub.bookmarkCount > 0 && (
                  <span className="shrink-0 text-[10px] text-muted-foreground/40 tabular-nums">
                    {sub.bookmarkCount}
                  </span>
                )}
              </button>
            ))}
          </div>
        ))}
      </div>

      <button
        type="button"
        className={cn(
          'mt-auto flex items-center gap-2 px-2 py-2 rounded-md text-xs text-muted-foreground hover:text-destructive hover:bg-destructive/5 transition-colors',
          activeGroupId === TRASH_GROUP_ID && 'text-destructive bg-destructive/5'
        )}
        onClick={() => setActiveGroup(TRASH_GROUP_ID)}
      >
        <Trash2 className="size-3.5" />
        <span>回收站</span>
      </button>
    </aside>
  )
}

export default SubGroupSidebar

// src/components/bookmarks/SubGroupSidebar.vue
<script setup lang="ts">
import { TRASH_GROUP_ID } from '@/stores/bookmark'

interface OutlineSubGroup {
  subGroupId: string
  subGroupName: string
  bookmarkCount: number
  anchorId: string
}

interface OutlineGroup {
  groupId: string
  groupName: string
  bookmarkCount: number
  children: OutlineSubGroup[]
}

const props = defineProps<{
  groups?: OutlineGroup[]
  activeAnchorId?: string
}>()

const emit = defineEmits<{
  (e: 'scroll-to', anchorId: string): void
  (e: 'edit-group', groupId: string): void
  (e: 'focus-search'): void
}>()

const store = useBookmarkStore()

// 如果没有传入 groups，从 store 计算（包含子分组）
const outlineGroups = computed<OutlineGroup[]>(() => {
  if (props.groups?.length) return props.groups

  return store.groups
    .filter(g => g.id !== TRASH_GROUP_ID)
    .map(group => {
      const children = group.children
        .filter(sub => (sub.bookmarkIds?.length || 0) > 0)
        .map(sub => ({
          subGroupId: sub.id,
          subGroupName: sub.name,
          bookmarkCount: sub.bookmarkIds?.length || 0,
          anchorId: `section-${group.id}-${sub.id}`,
        }))

      const bookmarkCount = children.reduce((sum, sub) => sum + sub.bookmarkCount, 0)

      return {
        groupId: group.id,
        groupName: group.name,
        bookmarkCount,
        children,
      }
    })
    .filter(g => g.bookmarkCount > 0)
})

const handleSubGroupClick = (anchorId: string) => {
  emit('scroll-to', anchorId)
  emit('focus-search')
}

const isSubGroupActive = (anchorId: string) => {
  if (!props.activeAnchorId) return false
  // 检查是否是当前激活 section 或其子 section
  return props.activeAnchorId === anchorId || anchorId.startsWith(`${props.activeAnchorId}-`)
}
</script>

<template>
  <aside class="shrink-0 w-36 flex flex-col overflow-y-auto no-scrollbar py-2 px-2 gap-1">
    <!-- Outline: Groups with SubGroups -->
    <div class="flex flex-col gap-2">
      <div
        v-for="group in outlineGroups"
        :key="group.groupId"
        class="flex flex-col gap-0.5"
      >
        <!-- Group Label -->
        <div class="px-2 py-1 text-[10px] font-semibold text-muted-foreground/50 uppercase tracking-wider">
          {{ group.groupName }}
        </div>
        <!-- SubGroups -->
        <button
          v-for="sub in group.children"
          :key="sub.subGroupId"
          class="group-nav-item relative flex items-center gap-2 pl-5 pr-2 py-1 rounded-md text-left text-xs transition-colors duration-120"
          :class="{
            'group-nav-item--active': isSubGroupActive(sub.anchorId),
            'group-nav-item--idle': !isSubGroupActive(sub.anchorId),
          }"
          @click="handleSubGroupClick(sub.anchorId)"
        >
          <span class="truncate flex-1">{{ sub.subGroupName }}</span>
          <span
            v-if="sub.bookmarkCount > 0"
            class="shrink-0 text-[10px] text-muted-foreground/40 tabular-nums"
          >
            {{ sub.bookmarkCount }}
          </span>
        </button>
      </div>
    </div>

    <!-- Trash -->
    <button
      class="mt-auto flex items-center gap-2 px-2 py-2 rounded-md text-xs text-muted-foreground hover:text-destructive hover:bg-destructive/5 transition-colors"
      :class="{ 'text-destructive bg-destructive/5': store.activeGroupId === TRASH_GROUP_ID }"
      @click="store.selectGroup(TRASH_GROUP_ID)"
    >
      <span class="i-ph-trash-thin text-sm" />
      <span>回收站</span>
    </button>
  </aside>
</template>

<style scoped>
.group-nav-item--idle {
  color: hsl(var(--muted-foreground));
}

.group-nav-item--idle:hover {
  color: hsl(var(--foreground));
  background-color: hsl(var(--muted) / 0.4);
}

.dark .group-nav-item--idle:hover {
  background-color: hsl(var(--muted) / 0.2);
}

.group-nav-item--active {
  color: hsl(var(--foreground));
  background-color: hsl(var(--muted) / 0.7);
  font-weight: 500;
}

.dark .group-nav-item--active {
  background-color: hsl(var(--muted) / 0.4);
}

.group-nav-item--active::before {
  content: '';
  position: absolute;
  left: 0;
  top: 50%;
  transform: translateY(-50%);
  width: 2px;
  height: 14px;
  border-radius: 0 2px 2px 0;
  background-color: hsl(var(--primary));
}

aside::-webkit-scrollbar {
  display: none;
}

aside {
  scrollbar-width: none;
  -ms-overflow-style: none;
}
</style>
