// src/views/settings/CategoryManager.vue
<script setup lang="ts">
import draggable from 'vuedraggable'
import ResultToast from '@/components/ResultToast.vue'
import { useCategoryEditor } from '@/composables/useCategoryEditor'
import type { Group } from '@/types/bookmark'
import { TRASH_GROUP_ID } from '@/stores/bookmark'

const store = useBookmarkStore()

// 编辑状态
const editingGroupId = ref('')
const editingSubId = ref('')
const editName = ref('')
const isAddingGroup = ref(false)
const newGroupName = ref('')
const addingSubGroupId = ref('')
const newSubName = ref('')
const addGroupInput = ref<InstanceType<typeof import('@/components/ui/input').Input> | null>(null)
const addSubInput = ref<InstanceType<typeof import('@/components/ui/input').Input> | null>(null)
const groupListRef = ref<HTMLElement | null>(null)
const groupRowRefs = ref<Record<string, HTMLElement | null>>({})
const isDragging = ref(false)
const { pendingCategoryEditorRequest, clearCategoryEditorRequest } = useCategoryEditor()

// 删除确认
const showDeleteConfirm = ref(false)
const deleteTarget = ref<{ type: 'group' | 'sub'; groupId: string; subId?: string; name: string } | null>(null)
const confirmDeleteButtonRef = ref<HTMLElement | null>(null)

// 撤回 Toast
const undoToast = ref<{ visible: boolean; message: string; data: { type: 'group' | 'sub'; groupId: string; subId?: string; name: string; groups: typeof store.groups; bookmarks: typeof store.bookmarks } | null }>({ visible: false, message: '', data: null })
let undoTimer: ReturnType<typeof setTimeout> | null = null

// Result Toast
type ResultToastVariant = 'success' | 'info' | 'warning' | 'error'
type ResultToastState = {
  visible: boolean
  variant: ResultToastVariant
  title: string
  description?: string
}
const resultToast = ref<ResultToastState>({
  visible: false,
  variant: 'info',
  title: ''
})
let resultToastTimer: ReturnType<typeof setTimeout> | null = null

const closeResultToast = () => {
  if (resultToastTimer) clearTimeout(resultToastTimer)
  resultToastTimer = null
  resultToast.value.visible = false
}

const showResultToast = (payload: Omit<ResultToastState, 'visible'>, timeoutMs = 4500) => {
  if (resultToastTimer) clearTimeout(resultToastTimer)
  resultToast.value = { ...payload, visible: true }
  resultToastTimer = setTimeout(() => closeResultToast(), timeoutMs)
}

const editingLocked = computed(() => 
  !!editingGroupId.value || 
  !!editingSubId.value || 
  isAddingGroup.value || 
  !!addingSubGroupId.value
)

// 可拖拽的分组列表 (排除回收站)
const draggableGroups = computed({
  get: () => (Array.isArray(store.groups) ? store.groups : []).filter(g => g.id !== TRASH_GROUP_ID),
  set: (val: Group[]) => store.reorderGroups(val)
})

// 拖拽配置
const dragOptions = computed(() => ({
  animation: 150,
  ghostClass: 'drag-ghost',
  chosenClass: 'drag-chosen',
  dragClass: 'drag-item',
  disabled: editingLocked.value,
  handle: '.drag-handle'
}))

// 子分组拖拽结束处理
const handleSubDragEnd = (evt: { oldIndex: number; newIndex: number; from: HTMLElement; to: HTMLElement; item: HTMLElement }) => {
  const fromGroupId = evt.from.dataset.groupId
  const toGroupId = evt.to.dataset.groupId
  const subId = evt.item.dataset.subId
  
  if (!fromGroupId || !subId) return
  
  // 如果拖到了升级区域，升级为主分组
  if (toGroupId === 'promote-zone') {
    store.promoteSubToGroup(fromGroupId, subId)
    return
  }
  
  // 如果跨分组移动
  if (toGroupId && fromGroupId !== toGroupId) {
    store.moveSubToGroup(fromGroupId, subId, toGroupId)
  }
}

// 禁止拖动分享/导入的子分组
const checkSubMove = (evt: { draggedContext: { element: { shareId?: string; sourceShareId?: string } } }) => {
  const sub = evt.draggedContext.element
  if (sub.shareId || sub.sourceShareId) {
    const msg = sub.shareId ? '分享中的分组无法移动' : '导入的分组无法移动'
    showResultToast({ variant: 'warning', title: msg }, 2000)
    return false
  }
  return true
}

// 编辑分组
const startEditGroup = (id: string, name: string) => {
  editingGroupId.value = id
  editingSubId.value = ''
  editName.value = name
}

const startEditSub = (groupId: string, subId: string, name: string) => {
  editingGroupId.value = groupId
  editingSubId.value = subId
  editName.value = name
}

const saveEdit = () => {
  if (!editName.value.trim()) return
  if (editingSubId.value) {
    store.updateSubGroup(editingGroupId.value, editingSubId.value, editName.value.trim())
  } else {
    store.updateGroup(editingGroupId.value, editName.value.trim())
  }
  editingGroupId.value = ''
  editingSubId.value = ''
  editName.value = ''
}

const isImeComposing = (event: KeyboardEvent) => {
  const keyboardEvent = event as KeyboardEvent & { keyCode?: number }
  return keyboardEvent.isComposing || keyboardEvent.keyCode === 229
}

const handleSubmitOnEnter = (event: KeyboardEvent, submit: () => void) => {
  if (event.key !== 'Enter' || isImeComposing(event)) return
  event.preventDefault()
  submit()
}

const cancelEdit = () => {
  editingGroupId.value = ''
  editingSubId.value = ''
  editName.value = ''
}

// 添加分组
const startAddGroup = () => {
  isAddingGroup.value = true
  newGroupName.value = ''
  nextTick(() => (addGroupInput.value?.$el as HTMLInputElement)?.focus())
}

const confirmAddGroup = () => {
  if (!newGroupName.value.trim()) return
  store.addGroup(newGroupName.value.trim())
  isAddingGroup.value = false
  newGroupName.value = ''
}

const startAddSub = (groupId: string) => {
  addingSubGroupId.value = groupId
  newSubName.value = ''
  nextTick(() => {
    const row = groupRowRefs.value[groupId]
    if (row) {
      row.scrollIntoView({ behavior: 'smooth', block: 'center' })
    } else if (groupListRef.value) {
      groupListRef.value.scrollTop = groupListRef.value.scrollHeight
    }
    (addSubInput.value?.$el as HTMLInputElement)?.focus()
  })
}

const confirmAddSub = () => {
  if (!newSubName.value.trim() || !addingSubGroupId.value) return
  store.addSubGroup(newSubName.value.trim(), addingSubGroupId.value)
  addingSubGroupId.value = ''
  newSubName.value = ''
}

const cancelAddSub = () => {
  setTimeout(() => {
    addingSubGroupId.value = ''
    newSubName.value = ''
  }, 100)
}

const scrollToRequestedGroup = async (request: { groupId: string; requestId: number } | null) => {
  if (!request?.groupId) return
  const group = draggableGroups.value.find(item => item.id === request.groupId)
  if (!group) {
    clearCategoryEditorRequest(request.requestId)
    return
  }

  isAddingGroup.value = false
  addingSubGroupId.value = ''
  cancelEdit()

  await nextTick()
  const row = groupRowRefs.value[group.id]
  row?.scrollIntoView({ behavior: 'smooth', block: 'center' })
  clearCategoryEditorRequest(request.requestId)
}

watch(pendingCategoryEditorRequest, (request) => {
  void scrollToRequestedGroup(request)
}, { immediate: true })

// 删除确认
const openDeleteConfirm = (type: 'group' | 'sub', groupId: string, name: string, subId?: string) => {
  deleteTarget.value = { type, groupId, subId, name }
  showDeleteConfirm.value = true
}

watch(showDeleteConfirm, (isOpen) => {
  if (isOpen) {
    nextTick(() => {
      const button = confirmDeleteButtonRef.value
      const el = button && '$el' in button ? (button as any).$el : button
      if (el && typeof el.focus === 'function') {
        el.focus()
      } else {
        const dialog = document.querySelector('[role="dialog"]')
        const confirmBtn = dialog?.querySelector('button[class*="destructive"]') as HTMLElement
        confirmBtn?.focus()
      }
    })
  }
})

const handleConfirmDelete = () => {
  if (!deleteTarget.value) return
  
  const snapshot = {
    type: deleteTarget.value.type,
    groupId: deleteTarget.value.groupId,
    subId: deleteTarget.value.subId,
    name: deleteTarget.value.name,
    groups: JSON.parse(JSON.stringify(store.groups)),
    bookmarks: JSON.parse(JSON.stringify(store.bookmarks))
  }
  
  let success = false
  if (deleteTarget.value.type === 'group') {
    success = store.removeGroup(deleteTarget.value.groupId)
  } else if (deleteTarget.value.subId) {
    success = store.removeSubGroup(deleteTarget.value.groupId, deleteTarget.value.subId)
  }
  
  if (!success) {
    showResultToast({ variant: 'warning', title: '无法删除', description: '默认分组或最后一个子分组不能删除' }, 4000)
    showDeleteConfirm.value = false
    deleteTarget.value = null
    return
  }

  showDeleteConfirm.value = false
  
  if (undoTimer) clearTimeout(undoTimer)
  undoToast.value = {
    visible: true,
    message: deleteTarget.value.type === 'group' 
      ? `分组 "${snapshot.name}" 已删除` 
      : `子分组 "${snapshot.name}" 已删除`,
    data: snapshot
  }
  
  undoTimer = setTimeout(() => {
    undoToast.value.visible = false
    undoToast.value.data = null
  }, 5000)
  
  deleteTarget.value = null
}

const handleUndo = () => {
  if (!undoToast.value.data) return
  store.groups.splice(0, store.groups.length, ...undoToast.value.data.groups)
  store.bookmarks.splice(0, store.bookmarks.length, ...undoToast.value.data.bookmarks)
  store.syncAllSharedEntities()
  if (undoTimer) clearTimeout(undoTimer)
  undoToast.value = { visible: false, message: '', data: null }
}

const closeUndoToast = () => {
  if (undoTimer) clearTimeout(undoTimer)
  undoToast.value = { visible: false, message: '', data: null }
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <div class="settings-block">
      <div class="settings-block__head">
        <h3 class="settings-block__title">分组管理</h3>
        <p class="settings-block__desc">管理分组和子分组，可拖拽调整顺序或移动位置</p>
      </div>
        <!-- Add Group -->
        <div class="pb-2">
          <div v-if="!isAddingGroup">
            <Button variant="outline" class="w-full h-9 border-dashed border-input hover:border-foreground/20 hover:text-foreground transition-colors" :disabled="editingLocked" @click="startAddGroup">
              <span class="i-ph-plus-thin mr-2" /> 新建分组
            </Button>
          </div>
          <div v-else class="flex gap-2 animate-in fade-in slide-in-from-top-2">
            <Input 
              ref="addGroupInput"
              v-model="newGroupName" 
              placeholder="输入分组名称" 
              class="flex-1 h-9"
              @keydown="handleSubmitOnEnter($event, confirmAddGroup)"
              autofocus
            />
            <Button size="icon" class="h-9 w-9 shrink-0" @click="confirmAddGroup">
              <span class="i-ph-check-thin text-lg" />
            </Button>
            <Button size="icon" variant="ghost" class="h-9 w-9 shrink-0" @click="isAddingGroup = false">
              <span class="i-ph-x-thin text-lg" />
            </Button>
          </div>
        </div>
        
        <!-- Promote zone -->
        <div
          v-if="isDragging"
          class="rounded-lg border-2 border-dashed border-input bg-muted/35 p-4 text-center text-sm text-muted-foreground transition-all"
          data-group-id="promote-zone"
        >
          <span class="i-ph-arrow-up-thin mr-2" />把子分组拖到这里，可升级为主分组
        </div>
        
        <!-- Group List -->
        <draggable
          v-model="draggableGroups"
          item-key="id"
          v-bind="dragOptions"
          class="flex flex-col gap-4"
          ref="groupListRef"
          @start="isDragging = true"
          @end="isDragging = false"
        >
          <template #item="{ element: group }">
            <div
              class="flex flex-col gap-2 group/row rounded-lg p-2 bg-muted/30 transition-all"
              :class="{ 'ring-2 ring-border': isDragging }"
              :ref="(el) => { groupRowRefs[group.id] = el as HTMLElement | null }"
            >
              <!-- Group Header -->
              <div class="flex items-center gap-2">
                <span
                  class="i-ph-dots-six-vertical-thin text-muted-foreground/50 drag-handle shrink-0"
                  :class="editingLocked ? 'cursor-not-allowed opacity-30' : 'cursor-grab active:cursor-grabbing'"
                />
                <span class="i-ph-folder-thin text-xl text-foreground shrink-0" />
                
                <div v-if="editingGroupId === group.id && !editingSubId" class="flex-1 flex gap-2 items-center">
                  <Input 
                    v-model="editName" 
                    class="flex-1 h-9"
                    @keydown="handleSubmitOnEnter($event, saveEdit)"
                    autofocus
                  />
                  <Button size="icon" class="h-9 w-9 shrink-0" @click="saveEdit">
                    <span class="i-ph-check-thin text-lg" />
                  </Button>
                  <Button size="icon" variant="ghost" class="h-9 w-9 shrink-0" @click="cancelEdit">
                    <span class="i-ph-x-thin text-lg" />
                  </Button>
                </div>
                <span v-else class="flex-1 text-sm font-bold text-foreground">{{ group.name }}</span>
                
                <div
                  class="flex items-center gap-1 opacity-0 group-hover/row:opacity-100 transition-opacity"
                  v-if="!(editingGroupId === group.id && !editingSubId)"
                >
                  <Button 
                    v-if="editingGroupId !== group.id" 
                    variant="ghost" 
                    size="icon"
                    class="h-7 w-7 text-muted-foreground hover:text-foreground"
                    title="重命名"
                    :disabled="editingLocked"
                    @click="startEditGroup(group.id, group.name)"
                  >
                    <span class="i-ph-textbox-thin text-base" />
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="icon"
                    class="h-7 w-7 text-muted-foreground hover:text-foreground"
                    title="添加子分组"
                    :disabled="editingLocked"
                    @click="startAddSub(group.id)"
                  >
                    <span class="i-ph-plus-thin text-base" />
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="icon"
                    class="h-7 w-7 text-muted-foreground hover:text-destructive"
                    title="删除分组"
                    :disabled="editingLocked"
                    @click="openDeleteConfirm('group', group.id, group.name)"
                  >
                    <span class="i-ph-trash-thin text-base" />
                  </Button>
                </div>
              </div>
              
              <!-- Sub Groups -->
              <draggable
                :model-value="group.children"
                @update:model-value="(val: any[]) => store.reorderSubGroups(group.id, val)"
                item-key="id"
                :group="{ name: 'sub-groups', pull: true, put: true }"
                :animation="250"
                ghost-class="drag-ghost"
                chosen-class="drag-chosen"
                class="pl-8 flex flex-col gap-1 min-h-[20px]"
                :data-group-id="group.id"
                @end="handleSubDragEnd"
                :move="checkSubMove"
                :disabled="editingLocked"
              >
                <template #item="{ element: sub }">
                  <div 
                    :key="sub.id" 
                    :data-sub-id="sub.id"
                    class="flex items-center gap-3 text-sm px-3 py-1.5 rounded-md hover:bg-muted/50 transition-colors group/sub"
                    :class="{
                      'border border-dashed border-input bg-muted/15': sub.shareId || sub.sourceShareId
                    }"
                  >
                    <span
                      v-if="!sub.shareId && !sub.sourceShareId"
                      class="i-ph-dots-six-vertical-thin text-muted-foreground/30 shrink-0"
                      :class="editingLocked ? 'cursor-not-allowed opacity-30' : 'cursor-grab active:cursor-grabbing'"
                    />
                    <span v-else class="w-4 shrink-0" />
                    <span class="i-ph-arrow-bend-down-right-thin text-muted-foreground/30 shrink-0" />
                    
                    <div v-if="editingSubId === sub.id" class="flex-1 flex gap-2 items-center">
                      <Input 
                        v-model="editName" 
                        class="flex-1 h-9 text-sm"
                        @keydown="handleSubmitOnEnter($event, saveEdit)"
                        autofocus
                      />
                      <Button size="icon" class="h-9 w-9 shrink-0" @click="saveEdit">
                        <span class="i-ph-check-thin text-lg" />
                      </Button>
                      <Button size="icon" variant="ghost" class="h-9 w-9 shrink-0" @click="cancelEdit">
                        <span class="i-ph-x-thin text-lg" />
                      </Button>
                    </div>
                    <span v-else class="flex-1 text-muted-foreground flex items-center gap-1.5">
                      {{ sub.name }}
                      <span v-if="sub.shareId" class="i-ph-share-network-thin text-xs text-muted-foreground" title="我分享的" />
                      <span v-else-if="sub.sourceShareId" class="i-ph-cloud-arrow-down-thin text-xs text-muted-foreground" title="我导入的" />
                    </span>
                    
                    <div class="flex items-center gap-1 opacity-0 group-hover/sub:opacity-100 transition-opacity">
                      <Button 
                        v-if="editingSubId !== sub.id" 
                        variant="ghost"
                        size="icon"
                        class="h-6 w-6 text-muted-foreground hover:text-foreground"
                        :disabled="editingLocked || !!sub.sourceShareId"
                        :title="sub.sourceShareId ? '导入的分组暂不支持重命名' : '重命名'"
                        @click="startEditSub(group.id, sub.id, sub.name)"
                      >
                        <span class="i-ph-pencil-simple-thin text-xs" />
                      </Button>
                      <Button 
                        variant="ghost"
                        size="icon"
                        class="h-6 w-6 text-muted-foreground hover:text-destructive"
                        title="删除子分组"
                        :disabled="editingLocked"
                        @click="openDeleteConfirm('sub', group.id, sub.name, sub.id)"
                      >
                        <span class="i-ph-x-thin text-xs" />
                      </Button>
                    </div>
                  </div>
                </template>
              </draggable>

              <!-- Add Sub Input -->
              <div v-if="addingSubGroupId === group.id" class="flex items-center gap-2 pl-8 mt-1 animate-in fade-in slide-in-from-left-2">
                <span class="i-ph-arrow-bend-down-right-thin text-muted-foreground shrink-0" />
                <Input 
                  ref="addSubInput"
                  v-model="newSubName" 
                  class="flex-1 h-9 text-sm"
                  placeholder="输入子分组名称"
                  @keydown="handleSubmitOnEnter($event, confirmAddSub)"
                  @blur="cancelAddSub"
                  autofocus
                />
                <Button size="icon" class="h-9 w-9 shrink-0" @click="confirmAddSub" @mousedown.prevent>
                  <span class="i-ph-check-thin text-lg" />
                </Button>
                <Button size="icon" variant="ghost" class="h-9 w-9 shrink-0" @click="addingSubGroupId = ''" @mousedown.prevent>
                  <span class="i-ph-x-thin text-lg" />
                </Button>
              </div>
            </div>
          </template>
        </draggable>
    </div>

    <!-- Delete Confirmation Dialog -->
    <Dialog :open="showDeleteConfirm" @update:open="v => { if (!v) showDeleteConfirm = false }">
      <DialogContent class="sm:max-w-md" @pointer-down-outside.prevent @interact-outside.prevent>
        <DialogHeader>
          <DialogTitle>确认删除？</DialogTitle>
          <DialogDescription>
            {{ deleteTarget?.type === 'group' ? '分组' : '子分组' }} "{{ deleteTarget?.name }}" 及其独有书签将被永久删除。
          </DialogDescription>
        </DialogHeader>
        <DialogFooter class="gap-3">
          <Button variant="ghost" @click="showDeleteConfirm = false">取消</Button>
          <Button ref="confirmDeleteButtonRef" variant="destructive" @click="handleConfirmDelete">
            确认删除
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>

    <!-- Undo Toast -->
    <Teleport to="body">
      <Transition
        enter-active-class="transition-all duration-300 ease-out"
        enter-from-class="opacity-0 translate-y-4"
        enter-to-class="opacity-100 translate-y-0"
        leave-active-class="transition-all duration-200 ease-in"
        leave-from-class="opacity-100 translate-y-0"
        leave-to-class="opacity-0 translate-y-4"
      >
        <div
          v-if="undoToast.visible"
          class="fixed bottom-4 right-4 z-[9999] flex items-center gap-3 px-4 py-3 rounded-lg border border-border bg-card shadow-lg backdrop-blur-sm"
        >
          <span class="i-ph-trash-thin text-lg text-destructive" />
          <span class="text-sm text-foreground">{{ undoToast.message }}</span>
          <Button size="sm" variant="outline" class="h-7 px-3 text-xs ml-2" @click="handleUndo">
            撤回
          </Button>
          <Button 
            variant="ghost"
            size="icon"
            class="ml-1 h-7 w-7" 
            @click="closeUndoToast"
            title="关闭"
          >
            <span class="i-ph-x-thin text-sm text-muted-foreground" />
          </Button>
        </div>
      </Transition>
    </Teleport>

    <ResultToast
      :open="resultToast.visible"
      :variant="resultToast.variant"
      :title="resultToast.title"
      :description="resultToast.description"
      @close="closeResultToast"
    />
  </div>
</template>

<style scoped>
.drag-ghost {
  opacity: 0.5;
  background: hsl(var(--muted));
  border: 2px dashed hsl(var(--border)) !important;
  border-radius: var(--radius-lg);
}

.drag-chosen {
  opacity: 1;
  background: hsl(var(--card));
  box-shadow: 0 8px 32px hsl(var(--foreground) / 0.08);
  border: 1px solid hsl(var(--border)) !important;
  border-radius: var(--radius-lg);
  transform: scale(1.01);
  transition: transform 0.15s ease, box-shadow 0.15s ease;
}

.drag-item {
  cursor: grabbing !important;
}

.drag-handle:hover {
  color: hsl(var(--foreground));
}

.drag-handle.cursor-grab[disabled="true"],
.drag-handle[disabled] {
  cursor: not-allowed !important;
  opacity: 0.3;
}
</style>

// src/views/settings/CategoryManager.tsx
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent
} from 'react'
import {
  DndContext,
  PointerSensor,
  useSensor,
  useSensors,
  closestCenter,
  useDroppable,
  type DragEndEvent,
  type DragStartEvent
} from '@dnd-kit/core'
import {
  SortableContext,
  useSortable,
  verticalListSortingStrategy,
  arrayMove
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import {
  Plus,
  Check,
  X,
  GripVertical,
  Folder,
  SquarePen,
  Pencil,
  Trash2,
  CornerDownRight,
  Share2,
  CloudDownload,
  ArrowUp
} from 'lucide-react'
import type { Group, SubGroup } from '@/types/bookmark'
import { useBookmarkStore, TRASH_GROUP_ID } from '@/stores/bookmark'
import { useCategoryEditor } from '@/hooks/useCategoryEditor'
import {
  Button,
  Input,
  SettingsBlock,
  Modal,
  ModalHeader,
  ModalTitle,
  ModalDescription,
  ModalFooter,
  ResultToast,
  type ResultToastState
} from './_ui'
import { getBookmarkMutations } from './_bookmarkActions'

const INITIAL_TOAST: ResultToastState = {
  visible: false,
  variant: 'info',
  title: ''
}

const isImeComposing = (event: KeyboardEvent) => {
  const e = event as KeyboardEvent & { keyCode?: number }
  return e.nativeEvent.isComposing || e.keyCode === 229
}

const isShared = (sub: SubGroup) =>
  !!(sub as SubGroup & { shareId?: string; sourceShareId?: string }).shareId ||
  !!(sub as SubGroup & { sourceShareId?: string }).sourceShareId

/* -------------------------- Sortable sub-group -------------------------- */

function SortableSubGroup({
  group,
  sub,
  editingSubId,
  editName,
  editingLocked,
  onEditName,
  onSaveEdit,
  onCancelEdit,
  onStartEdit,
  onDelete,
  onSubmitOnEnter
}: {
  group: Group
  sub: SubGroup
  editingSubId: string
  editName: string
  editingLocked: boolean
  onEditName: (v: string) => void
  onSaveEdit: () => void
  onCancelEdit: () => void
  onStartEdit: (groupId: string, subId: string, name: string) => void
  onDelete: (groupId: string, subId: string, name: string) => void
  onSubmitOnEnter: (e: KeyboardEvent, submit: () => void) => void
}) {
  const shared = isShared(sub)
  const sourceShareId = (sub as SubGroup & { sourceShareId?: string })
    .sourceShareId
  const shareId = (sub as SubGroup & { shareId?: string }).shareId

  const { attributes, listeners, setNodeRef, transform, transition, isDragging } =
    useSortable({
      id: `sub:${group.id}:${sub.id}`,
      data: { type: 'sub', groupId: group.id, subId: sub.id, shared },
      disabled: editingLocked || shared
    })

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1
  }

  const editing = editingSubId === sub.id

  return (
    <div
      ref={setNodeRef}
      style={style}
      className={`group/sub flex items-center gap-3 rounded-md px-3 py-1.5 text-sm transition-colors hover:bg-muted/50 ${
        shared ? 'border border-dashed border-input bg-muted/15' : ''
      }`}
    >
      {!shared ? (
        <span
          {...attributes}
          {...listeners}
          className={`shrink-0 text-muted-foreground/30 ${
            editingLocked
              ? 'cursor-not-allowed opacity-30'
              : 'cursor-grab active:cursor-grabbing'
          }`}
        >
          <GripVertical className="size-4" />
        </span>
      ) : (
        <span className="w-4 shrink-0" />
      )}
      <CornerDownRight className="size-4 shrink-0 text-muted-foreground/30" />

      {editing ? (
        <div className="flex flex-1 items-center gap-2">
          <Input
            value={editName}
            onChange={(e) => onEditName(e.target.value)}
            className="h-9 flex-1 text-sm"
            onKeyDown={(e) => onSubmitOnEnter(e, onSaveEdit)}
            autoFocus
          />
          <Button size="icon" className="size-9 shrink-0" onClick={onSaveEdit}>
            <Check className="size-5" />
          </Button>
          <Button
            size="icon"
            variant="ghost"
            className="size-9 shrink-0"
            onClick={onCancelEdit}
          >
            <X className="size-5" />
          </Button>
        </div>
      ) : (
        <span className="flex flex-1 items-center gap-1.5 text-muted-foreground">
          {sub.name}
          {shareId && (
            <Share2 className="size-3 text-muted-foreground" aria-label="我分享的" />
          )}
          {!shareId && sourceShareId && (
            <CloudDownload
              className="size-3 text-muted-foreground"
              aria-label="我导入的"
            />
          )}
        </span>
      )}

      {!editing && (
        <div className="flex items-center gap-1 opacity-0 transition-opacity group-hover/sub:opacity-100">
          <Button
            variant="ghost"
            size="icon"
            className="size-6 text-muted-foreground hover:text-foreground"
            disabled={editingLocked || !!sourceShareId}
            title={sourceShareId ? '导入的分组暂不支持重命名' : '重命名'}
            onClick={() => onStartEdit(group.id, sub.id, sub.name)}
          >
            <Pencil className="size-3.5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="size-6 text-muted-foreground hover:text-destructive"
            title="删除子分组"
            disabled={editingLocked}
            onClick={() => onDelete(group.id, sub.id, sub.name)}
          >
            <X className="size-3.5" />
          </Button>
        </div>
      )}
    </div>
  )
}

/* ---------------------------- Sortable group ---------------------------- */

function SortableGroup({
  group,
  isDraggingAny,
  ...rest
}: {
  group: Group
  isDraggingAny: boolean
  editingGroupId: string
  editingSubId: string
  editName: string
  editingLocked: boolean
  addingSubGroupId: string
  newSubName: string
  registerRow: (id: string, el: HTMLElement | null) => void
  onEditName: (v: string) => void
  onSaveEdit: () => void
  onCancelEdit: () => void
  onStartEditGroup: (id: string, name: string) => void
  onStartEditSub: (groupId: string, subId: string, name: string) => void
  onStartAddSub: (groupId: string) => void
  onDeleteGroup: (groupId: string, name: string) => void
  onDeleteSub: (groupId: string, subId: string, name: string) => void
  onConfirmAddSub: () => void
  onCancelAddSub: () => void
  onNewSubName: (v: string) => void
  onSubmitOnEnter: (e: KeyboardEvent, submit: () => void) => void
}) {
  const {
    editingGroupId,
    editingSubId,
    editName,
    editingLocked,
    addingSubGroupId,
    newSubName,
    registerRow,
    onEditName,
    onSaveEdit,
    onCancelEdit,
    onStartEditGroup,
    onStartEditSub,
    onStartAddSub,
    onDeleteGroup,
    onDeleteSub,
    onConfirmAddSub,
    onCancelAddSub,
    onNewSubName,
    onSubmitOnEnter
  } = rest

  const { attributes, listeners, setNodeRef, transform, transition } =
    useSortable({
      id: `group:${group.id}`,
      data: { type: 'group', groupId: group.id },
      disabled: editingLocked
    })
  const { setNodeRef: setDropRef } = useDroppable({
    id: `group-drop:${group.id}`,
    data: { type: 'group-droppable', groupId: group.id }
  })

  const style = {
    transform: CSS.Transform.toString(transform),
    transition
  }

  const editingThisGroup = editingGroupId === group.id && !editingSubId

  return (
    <div
      ref={(el) => {
        setNodeRef(el)
        registerRow(group.id, el)
      }}
      style={style}
      className={`group/row flex flex-col gap-2 rounded-lg bg-muted/30 p-2 transition-all ${
        isDraggingAny ? 'ring-2 ring-border' : ''
      }`}
    >
      {/* Group Header */}
      <div className="flex items-center gap-2">
        <span
          {...attributes}
          {...listeners}
          className={`shrink-0 text-muted-foreground/50 ${
            editingLocked
              ? 'cursor-not-allowed opacity-30'
              : 'cursor-grab active:cursor-grabbing'
          }`}
        >
          <GripVertical className="size-4" />
        </span>
        <Folder className="size-5 shrink-0 text-foreground" />

        {editingThisGroup ? (
          <div className="flex flex-1 items-center gap-2">
            <Input
              value={editName}
              onChange={(e) => onEditName(e.target.value)}
              className="h-9 flex-1"
              onKeyDown={(e) => onSubmitOnEnter(e, onSaveEdit)}
              autoFocus
            />
            <Button size="icon" className="size-9 shrink-0" onClick={onSaveEdit}>
              <Check className="size-5" />
            </Button>
            <Button
              size="icon"
              variant="ghost"
              className="size-9 shrink-0"
              onClick={onCancelEdit}
            >
              <X className="size-5" />
            </Button>
          </div>
        ) : (
          <span className="flex-1 text-sm font-bold text-foreground">
            {group.name}
          </span>
        )}

        {!editingThisGroup && (
          <div className="flex items-center gap-1 opacity-0 transition-opacity group-hover/row:opacity-100">
            {editingGroupId !== group.id && (
              <Button
                variant="ghost"
                size="icon"
                className="size-7 text-muted-foreground hover:text-foreground"
                title="重命名"
                disabled={editingLocked}
                onClick={() => onStartEditGroup(group.id, group.name)}
              >
                <SquarePen className="size-4" />
              </Button>
            )}
            <Button
              variant="ghost"
              size="icon"
              className="size-7 text-muted-foreground hover:text-foreground"
              title="添加子分组"
              disabled={editingLocked}
              onClick={() => onStartAddSub(group.id)}
            >
              <Plus className="size-4" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="size-7 text-muted-foreground hover:text-destructive"
              title="删除分组"
              disabled={editingLocked}
              onClick={() => onDeleteGroup(group.id, group.name)}
            >
              <Trash2 className="size-4" />
            </Button>
          </div>
        )}
      </div>

      {/* Sub Groups */}
      <div ref={setDropRef} className="flex min-h-[20px] flex-col gap-1 pl-8">
        <SortableContext
          items={group.children.map((s) => `sub:${group.id}:${s.id}`)}
          strategy={verticalListSortingStrategy}
        >
          {group.children.map((sub) => (
            <SortableSubGroup
              key={sub.id}
              group={group}
              sub={sub}
              editingSubId={editingSubId}
              editName={editName}
              editingLocked={editingLocked}
              onEditName={onEditName}
              onSaveEdit={onSaveEdit}
              onCancelEdit={onCancelEdit}
              onStartEdit={onStartEditSub}
              onDelete={onDeleteSub}
              onSubmitOnEnter={onSubmitOnEnter}
            />
          ))}
        </SortableContext>
      </div>

      {/* Add Sub Input */}
      {addingSubGroupId === group.id && (
        <div className="mt-1 flex items-center gap-2 pl-8 animate-in fade-in slide-in-from-left-2">
          <CornerDownRight className="size-4 shrink-0 text-muted-foreground" />
          <Input
            value={newSubName}
            onChange={(e) => onNewSubName(e.target.value)}
            className="h-9 flex-1 text-sm"
            placeholder="输入子分组名称"
            onKeyDown={(e) => onSubmitOnEnter(e, onConfirmAddSub)}
            onBlur={onCancelAddSub}
            autoFocus
          />
          <Button
            size="icon"
            className="size-9 shrink-0"
            onMouseDown={(e) => e.preventDefault()}
            onClick={onConfirmAddSub}
          >
            <Check className="size-5" />
          </Button>
          <Button
            size="icon"
            variant="ghost"
            className="size-9 shrink-0"
            onMouseDown={(e) => e.preventDefault()}
            onClick={onCancelAddSub}
          >
            <X className="size-5" />
          </Button>
        </div>
      )}
    </div>
  )
}

/* ---------------------------- Promote zone ----------------------------- */

function PromoteZone() {
  const { setNodeRef, isOver } = useDroppable({
    id: 'promote-zone',
    data: { type: 'promote-zone' }
  })
  return (
    <div
      ref={setNodeRef}
      className={`rounded-lg border-2 border-dashed p-4 text-center text-sm text-muted-foreground transition-all ${
        isOver ? 'border-primary bg-primary/10' : 'border-input bg-muted/35'
      }`}
    >
      <ArrowUp className="mr-2 inline size-4" />
      把子分组拖到这里，可升级为主分组
    </div>
  )
}

/* ----------------------------- Main view ------------------------------- */

type UndoSnapshot = {
  type: 'group' | 'sub'
  name: string
  groups: Group[]
  bookmarks: ReturnType<typeof useBookmarkStore.getState>['bookmarks']
}

/**
 * CategoryManager：分组管理（增删改、拖拽排序/跨分组移动/升级、删除确认与撤回）。
 * 对应旧 Vue views/settings/CategoryManager.vue，功能等价；无埋点。
 * 拖拽由 vuedraggable 迁移为 @dnd-kit。
 */
export default function CategoryManager() {
  const groups = useBookmarkStore((s) => s.groups)
  const mutations = useMemo(() => getBookmarkMutations(), [])
  const pendingCategoryEditorRequest = useCategoryEditor(
    (c) => c.pendingCategoryEditorRequest
  )
  const clearCategoryEditorRequest = useCategoryEditor(
    (c) => c.clearCategoryEditorRequest
  )

  const [editingGroupId, setEditingGroupId] = useState('')
  const [editingSubId, setEditingSubId] = useState('')
  const [editName, setEditName] = useState('')
  const [isAddingGroup, setIsAddingGroup] = useState(false)
  const [newGroupName, setNewGroupName] = useState('')
  const [addingSubGroupId, setAddingSubGroupId] = useState('')
  const [newSubName, setNewSubName] = useState('')
  const [isDragging, setIsDragging] = useState(false)

  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<{
    type: 'group' | 'sub'
    groupId: string
    subId?: string
    name: string
  } | null>(null)

  const [undoToast, setUndoToast] = useState<{
    visible: boolean
    message: string
    data: UndoSnapshot | null
  }>({ visible: false, message: '', data: null })
  const undoTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const [resultToast, setResultToast] =
    useState<ResultToastState>(INITIAL_TOAST)
  const resultTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const rowRefs = useRef<Record<string, HTMLElement | null>>({})

  const draggableGroups = useMemo(
    () =>
      (Array.isArray(groups) ? groups : []).filter(
        (g) => g.id !== TRASH_GROUP_ID
      ),
    [groups]
  )

  const editingLocked =
    !!editingGroupId || !!editingSubId || isAddingGroup || !!addingSubGroupId

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 4 } })
  )

  /* --------------------------- toasts ---------------------------------- */
  const closeResultToast = () => {
    if (resultTimer.current) clearTimeout(resultTimer.current)
    resultTimer.current = null
    setResultToast((prev) => ({ ...prev, visible: false }))
  }
  const showResultToast = (
    payload: Omit<ResultToastState, 'visible'>,
    timeoutMs = 4500
  ) => {
    if (resultTimer.current) clearTimeout(resultTimer.current)
    setResultToast({ ...payload, visible: true })
    resultTimer.current = setTimeout(closeResultToast, timeoutMs)
  }

  /* ---------------------------- editing -------------------------------- */
  const registerRow = (id: string, el: HTMLElement | null) => {
    rowRefs.current[id] = el
  }

  const startEditGroup = (id: string, name: string) => {
    setEditingGroupId(id)
    setEditingSubId('')
    setEditName(name)
  }
  const startEditSub = (groupId: string, subId: string, name: string) => {
    setEditingGroupId(groupId)
    setEditingSubId(subId)
    setEditName(name)
  }
  const cancelEdit = () => {
    setEditingGroupId('')
    setEditingSubId('')
    setEditName('')
  }
  const saveEdit = () => {
    if (!editName.trim()) return
    if (editingSubId) {
      mutations.updateSubGroup(editingGroupId, editingSubId, editName.trim())
    } else {
      mutations.updateGroup(editingGroupId, editName.trim())
    }
    cancelEdit()
  }

  const handleSubmitOnEnter = (event: KeyboardEvent, submit: () => void) => {
    if (event.key !== 'Enter' || isImeComposing(event)) return
    event.preventDefault()
    submit()
  }

  /* ----------------------------- add ----------------------------------- */
  const startAddGroup = () => {
    setIsAddingGroup(true)
    setNewGroupName('')
  }
  const confirmAddGroup = () => {
    if (!newGroupName.trim()) return
    mutations.addGroup(newGroupName.trim())
    setIsAddingGroup(false)
    setNewGroupName('')
  }
  const startAddSub = (groupId: string) => {
    setAddingSubGroupId(groupId)
    setNewSubName('')
    requestAnimationFrame(() => {
      rowRefs.current[groupId]?.scrollIntoView({
        behavior: 'smooth',
        block: 'center'
      })
    })
  }
  const confirmAddSub = () => {
    if (!newSubName.trim() || !addingSubGroupId) return
    mutations.addSubGroup(newSubName.trim(), addingSubGroupId)
    setAddingSubGroupId('')
    setNewSubName('')
  }
  const cancelAddSub = () => {
    setTimeout(() => {
      setAddingSubGroupId('')
      setNewSubName('')
    }, 100)
  }

  /* --------------------------- category editor jump -------------------- */
  useEffect(() => {
    const request = pendingCategoryEditorRequest
    if (!request?.groupId) return
    const group = draggableGroups.find((item) => item.id === request.groupId)
    if (!group) {
      clearCategoryEditorRequest(request.requestId)
      return
    }
    setIsAddingGroup(false)
    setAddingSubGroupId('')
    cancelEdit()
    requestAnimationFrame(() => {
      rowRefs.current[group.id]?.scrollIntoView({
        behavior: 'smooth',
        block: 'center'
      })
      clearCategoryEditorRequest(request.requestId)
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pendingCategoryEditorRequest])

  /* ------------------------------ drag --------------------------------- */
  const onDragStart = (_e: DragStartEvent) => {
    setIsDragging(true)
  }

  const onDragEnd = (event: DragEndEvent) => {
    setIsDragging(false)
    const { active, over } = event
    if (!over) return

    const activeData = active.data.current as
      | { type: 'group' | 'sub'; groupId: string; subId?: string; shared?: boolean }
      | undefined
    const overData = over.data.current as
      | {
          type: 'group' | 'sub' | 'group-droppable' | 'promote-zone'
          groupId?: string
          subId?: string
        }
      | undefined
    if (!activeData) return

    // 分组排序
    if (activeData.type === 'group') {
      if (active.id === over.id) return
      const oldIndex = draggableGroups.findIndex(
        (g) => `group:${g.id}` === active.id
      )
      const newIndex = draggableGroups.findIndex(
        (g) => `group:${g.id}` === over.id
      )
      if (oldIndex === -1 || newIndex === -1) return
      mutations.reorderGroups(arrayMove(draggableGroups, oldIndex, newIndex))
      return
    }

    // 子分组拖拽
    if (activeData.type === 'sub' && activeData.subId) {
      const fromGroupId = activeData.groupId
      const subId = activeData.subId

      // 升级为主分组
      if (overData?.type === 'promote-zone') {
        mutations.promoteSubToGroup(fromGroupId, subId)
        return
      }

      // 解析目标 group
      let toGroupId: string | undefined
      if (overData?.type === 'group-droppable') toGroupId = overData.groupId
      else if (overData?.type === 'sub') toGroupId = overData.groupId
      else if (overData?.type === 'group') toGroupId = overData.groupId
      if (!toGroupId) return

      // 同组内重排
      if (toGroupId === fromGroupId) {
        const grp = draggableGroups.find((g) => g.id === fromGroupId)
        if (!grp) return
        const oldIndex = grp.children.findIndex((s) => s.id === subId)
        const overSubId =
          overData?.type === 'sub' ? overData.subId : undefined
        const newIndex = overSubId
          ? grp.children.findIndex((s) => s.id === overSubId)
          : grp.children.length - 1
        if (oldIndex === -1 || newIndex === -1 || oldIndex === newIndex) return
        mutations.reorderSubGroups(
          fromGroupId,
          arrayMove(grp.children, oldIndex, newIndex)
        )
        return
      }

      // 跨分组移动（禁止分享/导入的子分组）
      if (activeData.shared) {
        showResultToast(
          { variant: 'warning', title: '分享/导入的分组无法移动' },
          2000
        )
        return
      }
      mutations.moveSubToGroup(fromGroupId, subId, toGroupId)
    }
  }

  /* ----------------------------- delete -------------------------------- */
  const openDeleteConfirm = (
    type: 'group' | 'sub',
    groupId: string,
    name: string,
    subId?: string
  ) => {
    setDeleteTarget({ type, groupId, subId, name })
    setShowDeleteConfirm(true)
  }

  const handleConfirmDelete = () => {
    if (!deleteTarget) return
    const snap = useBookmarkStore.getState()
    const snapshot: UndoSnapshot = {
      type: deleteTarget.type,
      name: deleteTarget.name,
      groups: JSON.parse(JSON.stringify(snap.groups)),
      bookmarks: JSON.parse(JSON.stringify(snap.bookmarks))
    }

    let success = false
    if (deleteTarget.type === 'group') {
      success = mutations.removeGroup(deleteTarget.groupId)
    } else if (deleteTarget.subId) {
      success = mutations.removeSubGroup(deleteTarget.groupId, deleteTarget.subId)
    }

    if (!success) {
      showResultToast(
        {
          variant: 'warning',
          title: '无法删除',
          description: '默认分组或最后一个子分组不能删除'
        },
        4000
      )
      setShowDeleteConfirm(false)
      setDeleteTarget(null)
      return
    }

    setShowDeleteConfirm(false)
    if (undoTimer.current) clearTimeout(undoTimer.current)
    setUndoToast({
      visible: true,
      message:
        deleteTarget.type === 'group'
          ? `分组 "${snapshot.name}" 已删除`
          : `子分组 "${snapshot.name}" 已删除`,
      data: snapshot
    })
    undoTimer.current = setTimeout(() => {
      setUndoToast({ visible: false, message: '', data: null })
    }, 5000)
    setDeleteTarget(null)
  }

  const handleUndo = () => {
    if (!undoToast.data) return
    useBookmarkStore.setState({
      groups: undoToast.data.groups,
      bookmarks: undoToast.data.bookmarks
    })
    mutations.syncAllSharedEntities()
    if (undoTimer.current) clearTimeout(undoTimer.current)
    setUndoToast({ visible: false, message: '', data: null })
  }

  const closeUndoToast = () => {
    if (undoTimer.current) clearTimeout(undoTimer.current)
    setUndoToast({ visible: false, message: '', data: null })
  }

  return (
    <div className="flex flex-col gap-3">
      <SettingsBlock
        title="分组管理"
        desc="管理分组和子分组，可拖拽调整顺序或移动位置"
      >
        {/* Add Group */}
        <div className="pb-2">
          {!isAddingGroup ? (
            <Button
              variant="outline"
              className="h-9 w-full border-dashed border-input transition-colors hover:border-foreground/20 hover:text-foreground"
              disabled={editingLocked}
              onClick={startAddGroup}
            >
              <Plus className="mr-2 size-4" /> 新建分组
            </Button>
          ) : (
            <div className="flex gap-2 animate-in fade-in slide-in-from-top-2">
              <Input
                value={newGroupName}
                onChange={(e) => setNewGroupName(e.target.value)}
                placeholder="输入分组名称"
                className="h-9 flex-1"
                onKeyDown={(e) => handleSubmitOnEnter(e, confirmAddGroup)}
                autoFocus
              />
              <Button
                size="icon"
                className="size-9 shrink-0"
                onClick={confirmAddGroup}
              >
                <Check className="size-5" />
              </Button>
              <Button
                size="icon"
                variant="ghost"
                className="size-9 shrink-0"
                onClick={() => setIsAddingGroup(false)}
              >
                <X className="size-5" />
              </Button>
            </div>
          )}
        </div>

        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragStart={onDragStart}
          onDragEnd={onDragEnd}
        >
          {/* Promote zone */}
          {isDragging && <PromoteZone />}

          <SortableContext
            items={draggableGroups.map((g) => `group:${g.id}`)}
            strategy={verticalListSortingStrategy}
          >
            <div className="flex flex-col gap-4">
              {draggableGroups.map((group) => (
                <SortableGroup
                  key={group.id}
                  group={group}
                  isDraggingAny={isDragging}
                  editingGroupId={editingGroupId}
                  editingSubId={editingSubId}
                  editName={editName}
                  editingLocked={editingLocked}
                  addingSubGroupId={addingSubGroupId}
                  newSubName={newSubName}
                  registerRow={registerRow}
                  onEditName={setEditName}
                  onSaveEdit={saveEdit}
                  onCancelEdit={cancelEdit}
                  onStartEditGroup={startEditGroup}
                  onStartEditSub={startEditSub}
                  onStartAddSub={startAddSub}
                  onDeleteGroup={(groupId, name) =>
                    openDeleteConfirm('group', groupId, name)
                  }
                  onDeleteSub={(groupId, subId, name) =>
                    openDeleteConfirm('sub', groupId, name, subId)
                  }
                  onConfirmAddSub={confirmAddSub}
                  onCancelAddSub={cancelAddSub}
                  onNewSubName={setNewSubName}
                  onSubmitOnEnter={handleSubmitOnEnter}
                />
              ))}
            </div>
          </SortableContext>
        </DndContext>
      </SettingsBlock>

      {/* Delete Confirmation Dialog */}
      <Modal
        open={showDeleteConfirm}
        onClose={() => setShowDeleteConfirm(false)}
      >
        <ModalHeader>
          <ModalTitle>确认删除？</ModalTitle>
          <ModalDescription>
            {deleteTarget?.type === 'group' ? '分组' : '子分组'} "
            {deleteTarget?.name}" 及其独有书签将被永久删除。
          </ModalDescription>
        </ModalHeader>
        <ModalFooter>
          <Button variant="ghost" onClick={() => setShowDeleteConfirm(false)}>
            取消
          </Button>
          <Button variant="destructive" onClick={handleConfirmDelete} autoFocus>
            确认删除
          </Button>
        </ModalFooter>
      </Modal>

      {/* Undo Toast */}
      {undoToast.visible && (
        <div className="fixed bottom-4 right-4 z-[9999] flex items-center gap-3 rounded-lg border border-border bg-card px-4 py-3 shadow-lg backdrop-blur-sm animate-in fade-in slide-in-from-bottom-4">
          <Trash2 className="size-5 text-destructive" />
          <span className="text-sm text-foreground">{undoToast.message}</span>
          <Button
            size="sm"
            variant="outline"
            className="ml-2 h-7 px-3 text-xs"
            onClick={handleUndo}
          >
            撤回
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="ml-1 size-7"
            onClick={closeUndoToast}
            title="关闭"
          >
            <X className="size-4 text-muted-foreground" />
          </Button>
        </div>
      )}

      <ResultToast
        open={resultToast.visible}
        variant={resultToast.variant}
        title={resultToast.title}
        description={resultToast.description}
        onClose={closeResultToast}
      />
    </div>
  )
}
