// src/views/settings/GeneralSettings.vue
<script setup lang="ts">
import { ACCENT_PRESETS } from '@/constants/accent'

const settingsStore = useSettingsStore()

const { isUTools, isDark } = useAppState()

const easterEggEnabled = computed({
  get: () => settingsStore.easterEggEnabled,
  set: (val) => {
    settingsStore.setEasterEggEnabled(val)
  }
})

const viewModeOptions: Array<{ value: 'list' | 'grid' | 'cards'; label: string }> = [
  { value: 'list', label: '列表' },
  { value: 'grid', label: '卡片' },
  { value: 'cards', label: '画报' }
]

// 搜索结果仅支持列表 / 卡片两态（画报模式仅主页可用）
const searchViewModeOptions: Array<{ value: 'list' | 'grid'; label: string }> = [
  { value: 'list', label: '列表' },
  { value: 'grid', label: '卡片' }
]

const densityOptions: Array<{ value: 'compact' | 'regular' | 'comfy'; label: string }> = [
  { value: 'compact', label: '紧凑' },
  { value: 'regular', label: '常规' },
  { value: 'comfy', label: '舒适' }
]

const gridColumnsOptions = [2, 3, 4, 5]

const handleGridColumnsChange = (value: string | number) => {
  const next = typeof value === 'number' ? value : Number(value)
  if (Number.isFinite(next)) {
    settingsStore.setGridColumns(next)
  }
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <!-- 视图 -->
    <div class="settings-block">
      <div class="settings-block__head">
        <h3 class="settings-block__title">视图</h3>
        <p class="settings-block__desc">控制主页和搜索结果默认使用列表还是卡片模式</p>
      </div>
      <div class="space-y-4">
        <div class="settings-row">
          <div class="space-y-0.5">
            <div class="text-sm font-medium">主页默认展示</div>
            <div class="text-xs text-muted-foreground">打开书签页时，默认进入的内容布局</div>
          </div>
          <div class="flex gap-2 shrink-0">
            <Button
              v-for="opt in viewModeOptions"
              :key="`home-${opt.value}`"
              size="sm"
              :variant="settingsStore.homeViewMode === opt.value ? 'default' : 'ghost'"
              class="h-8 min-w-16 px-3"
              @click="settingsStore.setHomeViewMode(opt.value)"
            >
              {{ opt.label }}
            </Button>
          </div>
        </div>

        <div class="settings-row">
          <div class="space-y-0.5">
            <div class="text-sm font-medium">搜索结果默认展示</div>
            <div class="text-xs text-muted-foreground">进入搜索结果浮层时，默认展示方式会被记住</div>
          </div>
          <div class="flex gap-2 shrink-0">
            <Button
              v-for="opt in searchViewModeOptions"
              :key="`search-${opt.value}`"
              size="sm"
              :variant="settingsStore.searchViewMode === opt.value ? 'default' : 'ghost'"
              class="h-8 min-w-16 px-3"
              @click="settingsStore.setSearchViewMode(opt.value)"
            >
              {{ opt.label }}
            </Button>
          </div>
        </div>

        <div class="settings-row">
          <div class="space-y-0.5">
            <div class="text-sm font-medium">卡片每行数量</div>
            <div class="text-xs text-muted-foreground">仅卡片模式生效</div>
          </div>
          <div class="flex gap-1.5 shrink-0">
            <Button
              v-for="opt in gridColumnsOptions"
              :key="opt"
              size="sm"
              :variant="settingsStore.gridColumns === opt ? 'default' : 'ghost'"
              class="h-8 w-10 px-0 shrink-0"
              @click="handleGridColumnsChange(opt)"
            >
              {{ opt }}
            </Button>
          </div>
        </div>

        <div class="settings-row">
          <div class="space-y-0.5">
            <div class="text-sm font-medium">默认收起详情栏</div>
            <div class="text-xs text-muted-foreground">列表模式下，点击直接打开书签而不先展示详情</div>
          </div>
          <Switch
            :model-value="settingsStore.previewPanelCollapsed"
            aria-label="默认收起详情栏"
            @update:model-value="(checked: boolean) => settingsStore.setPreviewPanelCollapsed(checked)"
          />
        </div>

        <div class="settings-row">
          <div class="space-y-0.5">
            <div class="text-sm font-medium">信息密度</div>
            <div class="text-xs text-muted-foreground">控制列表/卡片中书签条目的行高与间距</div>
          </div>
          <div class="flex gap-2 shrink-0">
            <Button
              v-for="opt in densityOptions"
              :key="opt.value"
              size="sm"
              :variant="settingsStore.density === opt.value ? 'default' : 'ghost'"
              class="h-8 min-w-16 px-3"
              @click="settingsStore.setDensity(opt.value)"
            >
              {{ opt.label }}
            </Button>
          </div>
        </div>
      </div>
    </div>

    <!-- 强调色 -->
    <div class="settings-block">
      <div class="settings-block__head">
        <h3 class="settings-block__title">强调色</h3>
        <p class="settings-block__desc">主操作按钮、选中状态、链接等使用的颜色</p>
      </div>
      <div class="settings-row">
        <div class="space-y-0.5">
          <div class="text-sm font-medium">主题颜色</div>
          <div class="text-xs text-muted-foreground">选中项目将带有环形描边高亮</div>
        </div>
        <div class="flex gap-2.5 shrink-0">
          <button
            v-for="preset in ACCENT_PRESETS"
            :key="preset.id"
            type="button"
            :title="preset.name"
            class="accent-swatch"
            :style="{
              background: preset.swatch,
              boxShadow: settingsStore.accentColor === preset.id
                ? `0 0 0 2px hsl(var(--background)), 0 0 0 4px ${preset.swatch}`
                : 'none'
            }"
            @click="settingsStore.setAccentColor(preset.id)"
          />
        </div>
      </div>
    </div>

    <!-- 外观 -->
    <div v-if="isDark" class="settings-block">
      <div class="settings-block__head">
        <h3 class="settings-block__title">外观</h3>
        <p class="settings-block__desc">控制深色模式下的背景显示效果</p>
      </div>
      <div class="flex gap-3">
        <Button
          :variant="!settingsStore.useSolidBackground ? 'default' : 'ghost'"
          class="flex-1 h-auto py-3 px-4 justify-start gap-3"
          @click="settingsStore.setUseSolidBackground(false)"
        >
          <div class="sky-preview shrink-0" aria-hidden="true">
            <span class="sky-preview__main" />
            <span class="sky-preview__dot sky-preview__dot--1" />
            <span class="sky-preview__dot sky-preview__dot--2" />
            <span class="sky-preview__dot sky-preview__dot--3" />
          </div>
          <div class="text-left">
            <div class="text-sm font-medium">星空背景</div>
            <div class="text-xs text-muted-foreground">旋转星点与随机流星</div>
          </div>
        </Button>
        <Button
          :variant="settingsStore.useSolidBackground ? 'default' : 'ghost'"
          class="flex-1 h-auto py-3 px-4 justify-start gap-3"
          @click="settingsStore.setUseSolidBackground(true)"
        >
          <div class="background-preview background-preview--dark shrink-0" aria-hidden="true">
            <span class="i-ph-moon-thin text-lg text-white/85" />
          </div>
          <div class="text-left">
            <div class="text-sm font-medium">纯色背景</div>
            <div class="text-xs text-muted-foreground">沉浸纯净，更聚焦内容</div>
          </div>
        </Button>
      </div>
    </div>

    <!-- 窗口行为（uTools only） -->
    <div v-if="isUTools" class="settings-block">
      <div class="settings-block__head">
        <h3 class="settings-block__title">窗口行为</h3>
        <p class="settings-block__desc">控制独立窗口的关闭方式</p>
      </div>
      <div class="settings-row">
        <div class="space-y-0.5">
          <div class="text-sm font-medium">独立窗口自动关闭</div>
          <div class="text-xs text-muted-foreground">独立窗口打开书签后自动关闭当前窗口</div>
        </div>
        <Switch
          :model-value="settingsStore.autoCloseWindow"
          aria-label="独立窗口自动关闭"
          @update:model-value="(checked: boolean) => settingsStore.setAutoCloseWindow(checked)"
        />
      </div>
    </div>

  </div>
</template>

<style scoped>
.accent-swatch {
  width: 1.5rem;
  height: 1.5rem;
  border-radius: 9999px;
  border: none;
  cursor: pointer;
  flex-shrink: 0;
  transition: transform 100ms ease, box-shadow 100ms ease;
}

.accent-swatch:hover {
  transform: scale(1.12);
}

.background-preview {
  width: 2.5rem;
  height: 2.5rem;
  border-radius: 0.75rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.background-preview--dark {
  background: linear-gradient(180deg, #3a3d41 0%, #2f3133 100%);
  box-shadow: inset 0 1px 0 rgb(255 255 255 / 0.06);
}

.background-preview--white {
  background: linear-gradient(180deg, #ffffff 0%, #f6f7f8 100%);
  box-shadow: inset 0 1px 0 rgb(255 255 255 / 0.8);
}

.background-preview--soft {
  background: linear-gradient(180deg, #f4f4f4 0%, #ececec 100%);
}
</style>

<style scoped>
.sky-preview {
  position: relative;
  width: 2.5rem;
  height: 2.5rem;
  border-radius: 0.625rem;
  overflow: hidden;
  background:
    radial-gradient(circle at 50% -5%, rgb(25 53 84 / 0.95), transparent 52%),
    linear-gradient(180deg, #08111c 0%, #020204 62%, #000000 100%);
  box-shadow:
    inset 0 1px 0 rgb(255 255 255 / 0.08),
    0 10px 20px rgb(0 0 0 / 0.18);
}

.sky-preview::before {
  content: '';
  position: absolute;
  inset: 0;
  background: radial-gradient(circle at 50% 0%, rgb(148 201 255 / 0.18), transparent 48%);
}

.sky-preview::after {
  content: '';
  position: absolute;
  top: 5px;
  left: -10px;
  width: 32px;
  height: 1px;
  background: linear-gradient(90deg, rgb(255 255 255 / 0), rgb(255 255 255 / 0.92), rgb(255 255 255 / 0));
  transform: rotate(25deg);
  animation: sky-meteor 3.6s ease-in-out infinite;
}

.sky-preview__main {
  position: absolute;
  top: 8px;
  left: 9px;
  width: 7px;
  height: 7px;
  border-radius: 9999px;
  background: rgb(226 238 255 / 0.92);
  box-shadow:
    0 0 8px rgb(173 216 255 / 0.65),
    0 0 14px rgb(173 216 255 / 0.3);
  animation: sky-twinkle 2.4s ease-in-out infinite;
}

.sky-preview__dot {
  position: absolute;
  width: 2.5px;
  height: 2.5px;
  border-radius: 9999px;
  background: rgb(225 235 255 / 0.82);
  box-shadow: 0 0 5px rgb(173 216 255 / 0.38);
  animation: sky-dot 2.8s ease-in-out infinite;
}

.sky-preview__dot--1 { top: 10px; right: 9px; animation-delay: 0.2s; }
.sky-preview__dot--2 { top: 18px; left: 8px; animation-delay: 0.7s; }
.sky-preview__dot--3 { top: 22px; right: 12px; animation-delay: 1.2s; }

@keyframes sky-twinkle {
  0%, 100% { opacity: 0.5; transform: scale(0.86); }
  50% { opacity: 1; transform: scale(1.18); }
}
@keyframes sky-dot {
  0%, 100% { opacity: 0.25; transform: scale(0.85); }
  50% { opacity: 0.85; transform: scale(1.12); }
}
@keyframes sky-meteor {
  0%, 58%, 100% { opacity: 0; transform: translate(-10px, -6px) rotate(25deg); }
  70% { opacity: 0.9; }
  84% { opacity: 0; transform: translate(24px, 16px) rotate(25deg); }
}
</style>

// src/views/settings/GeneralSettings.tsx
import { Moon } from 'lucide-react'
import { ACCENT_PRESETS } from '@/constants/accent'
import { useSettingsStore } from '@/stores/settings'
import { useAppState } from '@/hooks/useAppState'
import { Button, Switch, SettingsBlock, SettingsRow } from './_ui'
import type { ViewMode, Density } from '@/stores/settings'

const viewModeOptions: Array<{ value: ViewMode; label: string }> = [
  { value: 'list', label: '列表' },
  { value: 'grid', label: '卡片' },
  { value: 'cards', label: '画报' }
]

// 搜索结果仅支持列表 / 卡片两态（画报模式仅主页可用）
const searchViewModeOptions: Array<{ value: 'list' | 'grid'; label: string }> = [
  { value: 'list', label: '列表' },
  { value: 'grid', label: '卡片' }
]

const densityOptions: Array<{ value: Density; label: string }> = [
  { value: 'compact', label: '紧凑' },
  { value: 'regular', label: '常规' },
  { value: 'comfy', label: '舒适' }
]

const gridColumnsOptions = [2, 3, 4, 5]

/**
 * GeneralSettings：通用设置（视图 / 强调色 / 外观 / 窗口行为）。
 * 对应旧 Vue views/settings/GeneralSettings.vue，功能等价；无埋点。
 */
export default function GeneralSettings() {
  const s = useSettingsStore()
  const { isUTools, isDark } = useAppState()

  return (
    <div className="flex flex-col gap-3">
      {/* 视图 */}
      <SettingsBlock
        title="视图"
        desc="控制主页和搜索结果默认使用列表还是卡片模式"
      >
        <div className="space-y-4">
          <SettingsRow
            label="主页默认展示"
            hint="打开书签页时，默认进入的内容布局"
          >
            <div className="flex shrink-0 gap-2">
              {viewModeOptions.map((opt) => (
                <Button
                  key={`home-${opt.value}`}
                  size="sm"
                  variant={s.homeViewMode === opt.value ? 'default' : 'ghost'}
                  className="h-8 min-w-16 px-3"
                  onClick={() => s.setHomeViewMode(opt.value)}
                >
                  {opt.label}
                </Button>
              ))}
            </div>
          </SettingsRow>

          <SettingsRow
            label="搜索结果默认展示"
            hint="进入搜索结果浮层时，默认展示方式会被记住"
          >
            <div className="flex shrink-0 gap-2">
              {searchViewModeOptions.map((opt) => (
                <Button
                  key={`search-${opt.value}`}
                  size="sm"
                  variant={s.searchViewMode === opt.value ? 'default' : 'ghost'}
                  className="h-8 min-w-16 px-3"
                  onClick={() => s.setSearchViewMode(opt.value)}
                >
                  {opt.label}
                </Button>
              ))}
            </div>
          </SettingsRow>

          <SettingsRow label="卡片每行数量" hint="仅卡片模式生效">
            <div className="flex shrink-0 gap-1.5">
              {gridColumnsOptions.map((opt) => (
                <Button
                  key={opt}
                  size="sm"
                  variant={s.gridColumns === opt ? 'default' : 'ghost'}
                  className="h-8 w-10 shrink-0 px-0"
                  onClick={() => s.setGridColumns(opt)}
                >
                  {opt}
                </Button>
              ))}
            </div>
          </SettingsRow>

          <SettingsRow
            label="默认收起详情栏"
            hint="列表模式下，点击直接打开书签而不先展示详情"
          >
            <Switch
              checked={s.previewPanelCollapsed}
              aria-label="默认收起详情栏"
              onChange={(checked) => s.setPreviewPanelCollapsed(checked)}
            />
          </SettingsRow>

          <SettingsRow
            label="信息密度"
            hint="控制列表/卡片中书签条目的行高与间距"
          >
            <div className="flex shrink-0 gap-2">
              {densityOptions.map((opt) => (
                <Button
                  key={opt.value}
                  size="sm"
                  variant={s.density === opt.value ? 'default' : 'ghost'}
                  className="h-8 min-w-16 px-3"
                  onClick={() => s.setDensity(opt.value)}
                >
                  {opt.label}
                </Button>
              ))}
            </div>
          </SettingsRow>
        </div>
      </SettingsBlock>

      {/* 强调色 */}
      <SettingsBlock
        title="强调色"
        desc="主操作按钮、选中状态、链接等使用的颜色"
      >
        <SettingsRow label="主题颜色" hint="选中项目将带有环形描边高亮">
          <div className="flex shrink-0 gap-2.5">
            {ACCENT_PRESETS.map((preset) => (
              <button
                key={preset.id}
                type="button"
                title={preset.name}
                className="accent-swatch"
                style={{
                  background: preset.swatch,
                  boxShadow:
                    s.accentColor === preset.id
                      ? `0 0 0 2px hsl(var(--background)), 0 0 0 4px ${preset.swatch}`
                      : 'none'
                }}
                onClick={() => s.setAccentColor(preset.id)}
              />
            ))}
          </div>
        </SettingsRow>
      </SettingsBlock>

      {/* 外观（仅深色模式） */}
      {isDark && (
        <SettingsBlock title="外观" desc="控制深色模式下的背景显示效果">
          <div className="flex gap-3">
            <Button
              variant={!s.useSolidBackground ? 'default' : 'ghost'}
              className="h-auto flex-1 justify-start gap-3 px-4 py-3"
              onClick={() => s.setUseSolidBackground(false)}
            >
              <div className="sky-preview shrink-0" aria-hidden="true">
                <span className="sky-preview__main" />
                <span className="sky-preview__dot sky-preview__dot--1" />
                <span className="sky-preview__dot sky-preview__dot--2" />
                <span className="sky-preview__dot sky-preview__dot--3" />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium">星空背景</div>
                <div className="text-xs text-muted-foreground">
                  旋转星点与随机流星
                </div>
              </div>
            </Button>
            <Button
              variant={s.useSolidBackground ? 'default' : 'ghost'}
              className="h-auto flex-1 justify-start gap-3 px-4 py-3"
              onClick={() => s.setUseSolidBackground(true)}
            >
              <div
                className="background-preview background-preview--dark shrink-0"
                aria-hidden="true"
              >
                <Moon className="size-5 text-white/85" />
              </div>
              <div className="text-left">
                <div className="text-sm font-medium">纯色背景</div>
                <div className="text-xs text-muted-foreground">
                  沉浸纯净，更聚焦内容
                </div>
              </div>
            </Button>
          </div>
        </SettingsBlock>
      )}

      {/* 窗口行为（仅 uTools） */}
      {isUTools && (
        <SettingsBlock title="窗口行为" desc="控制独立窗口的关闭方式">
          <SettingsRow
            label="独立窗口自动关闭"
            hint="独立窗口打开书签后自动关闭当前窗口"
          >
            <Switch
              checked={s.autoCloseWindow}
              aria-label="独立窗口自动关闭"
              onChange={(checked) => s.setAutoCloseWindow(checked)}
            />
          </SettingsRow>
        </SettingsBlock>
      )}
    </div>
  )
}
