// src/components/ContextMenu.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, nextTick } from 'vue'
import type { CSSProperties } from 'vue'

const props = defineProps<{
  x: number
  y: number
  isTrash?: boolean
  readonly?: boolean
  isUTools?: boolean
  hasDescription?: boolean
}>()

const emit = defineEmits<{
  close: []
  action: [string]
}>()

const menu = ref<HTMLElement | null>(null)
const isPositioned = ref(false)
const menuStyle = ref<CSSProperties>({
  top: '0px',
  left: '0px',
  visibility: 'hidden'
})

const EDGE_GAP = 8

const updatePosition = async () => {
  isPositioned.value = false
  await nextTick()

  const el = menu.value
  if (!el) return

  const rect = el.getBoundingClientRect()
  const viewWidth = window.innerWidth
  const viewHeight = window.innerHeight

  let left = props.x
  let top = props.y

  if (left + rect.width > viewWidth - EDGE_GAP) {
    left = viewWidth - rect.width - EDGE_GAP
  }
  if (top + rect.height > viewHeight - EDGE_GAP) {
    top = props.y - rect.height
  }

  left = Math.max(EDGE_GAP, left)
  top = Math.max(EDGE_GAP, top)

  menuStyle.value = {
    top: `${Math.round(top)}px`,
    left: `${Math.round(left)}px`,
    visibility: 'visible'
  }
  isPositioned.value = true
}

const handleClickOutside = (e: Event) => {
  if (menu.value && !menu.value.contains(e.target as Node)) {
    emit('close')
  }
}

const handleAction = (action: string) => {
  emit('action', action)
  emit('close')
}

onMounted(() => {
  void updatePosition()
  document.addEventListener('click', handleClickOutside)
  document.addEventListener('contextmenu', handleClickOutside)
  document.addEventListener('scroll', handleClickOutside, true)
  window.addEventListener('resize', updatePosition)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  document.removeEventListener('contextmenu', handleClickOutside)
  document.removeEventListener('scroll', handleClickOutside, true)
  window.removeEventListener('resize', updatePosition)
})

watch(
  () => [props.x, props.y],
  () => {
    void updatePosition()
  }
)
</script>

<template>
  <div
    ref="menu"
    class="context-menu fixed z-[10000] min-w-[160px] bg-white/90 dark:bg-[#1a1c20]/90 backdrop-blur-md rounded-xl shadow-xl border border-white/10 p-1.5 flex flex-col gap-1 text-sm animate-fade-in"
    :style="menuStyle"
    :class="{ 'pointer-events-none': !isPositioned }"
    @click.stop
    @contextmenu.prevent
  >
    <template v-if="!isTrash">
      <Button variant="ghost" class="menu-item justify-start" @click="handleAction('open')">
        <span class="i-ph-arrow-square-out-thin text-muted" />
        <span>打开链接</span>
      </Button>

      <Button v-if="isUTools" variant="ghost" class="menu-item justify-start" @click="handleAction('openInUtoolsBrowser')">
        <span class="i-ph-globe-thin text-muted" />
        <span>使用 uTools 浏览器打开</span>
      </Button>

      <Button variant="ghost" class="menu-item justify-start" @click="handleAction('copy')">
        <span class="i-ph-copy-thin text-muted" />
        <span>复制链接</span>
      </Button>

      <Button
        variant="ghost"
        class="menu-item justify-start"
        :disabled="!hasDescription"
        @click="handleAction('copyDescription')"
      >
        <span class="i-ph-article-thin text-muted" />
        <span>复制描述</span>
      </Button>
  
      <template v-if="!readonly">
        <div class="h-px bg-white/10 mx-1" />

        <Button variant="ghost" class="menu-item justify-start" @click="handleAction('edit')">
          <span class="i-ph-pencil-simple-thin text-muted" />
          <span>编辑</span>
        </Button>

        <div class="h-px bg-white/10 mx-1" />
        
        <Button variant="ghost" class="menu-item justify-start text-red-500 hover:!text-red-600 hover:!bg-red-500/10" @click="handleAction('remove')">
          <span class="i-ph-trash-thin" />
          <span>移除</span>
        </Button>
      </template>
    </template>

    <template v-else>
      <Button variant="ghost" class="menu-item justify-start text-primary" @click="handleAction('restore')">
        <span class="i-ph-arrow-counter-clockwise-thin" />
        <span>还原</span>
      </Button>

      <div class="h-px bg-white/10 mx-1" />

      <Button variant="ghost" class="menu-item justify-start text-red-500 hover:!text-red-600 hover:!bg-red-500/10" @click="handleAction('remove')">
        <span class="i-ph-trash-simple-thin" />
        <span>彻底删除</span>
      </Button>
    </template>
  </div>
</template>

<style scoped>
@reference "../assets/index.css";

.menu-item {
  @apply flex items-center gap-2.5 px-3 py-2 rounded-lg hover:bg-black/5 dark:hover:bg-white/10 text-[var(--fg)] transition-colors text-left w-full;
}
.animate-fade-in {
  animation: fadeIn 0.1s ease-out;
}
@keyframes fadeIn {
  from { opacity: 0; transform: scale(0.98); }
  to { opacity: 1; transform: scale(1); }
}
</style>

// src/components/ContextMenu.tsx
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import type { CSSProperties, ReactNode } from 'react'
import {
  ExternalLink,
  Globe,
  Copy,
  FileText,
  Pencil,
  Pin,
  Folder,
  Trash2,
  CornerUpLeft
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * ContextMenu（React 版）
 * --------------------------------------------------------------------------
 * 旧版 Vue ref + onMounted 监听 + watch(x,y) 重定位 → React useState + useEffect。
 * 通过 portal 挂到 body，挂载/坐标变化后用 useLayoutEffect 量取尺寸做边缘避让。
 * i-ph-* 图标改为 lucide-react；scoped @apply 样式内联为 Tailwind class。
 */
export type ContextMenuAction =
  | 'open'
  | 'openInUtoolsBrowser'
  | 'copy'
  | 'copyDescription'
  | 'edit'
  | 'pin'
  | 'locate'
  | 'remove'
  | 'restore'

export interface ContextMenuProps {
  x: number
  y: number
  isTrash?: boolean
  readonly?: boolean
  isUTools?: boolean
  hasDescription?: boolean
  onClose: () => void
  onAction: (action: ContextMenuAction) => void
}

const EDGE_GAP = 8

const ITEM_CLASS =
  'flex items-center gap-[9px] h-[30px] px-[10px] rounded-[7px] text-[13px] text-foreground text-left w-full transition-colors cursor-default select-none hover:bg-muted disabled:opacity-40 disabled:cursor-not-allowed'
const DANGER_ITEM_CLASS = 'text-destructive hover:bg-destructive/10'
const ICON_CLASS = 'w-4 shrink-0 size-[14px] text-muted-foreground'
const DANGER_ICON_CLASS = 'w-4 shrink-0 size-[14px] text-destructive'
const DIVIDER_CLASS = 'h-px bg-border my-[4px] mx-[6px]'

function MenuItem({
  icon: Icon,
  label,
  danger,
  disabled,
  onClick
}: {
  icon: LucideIcon
  label: ReactNode
  danger?: boolean
  disabled?: boolean
  onClick: () => void
}) {
  return (
    <button
      type="button"
      className={cn(ITEM_CLASS, danger && DANGER_ITEM_CLASS)}
      disabled={disabled}
      onClick={onClick}
    >
      <Icon className={danger ? DANGER_ICON_CLASS : ICON_CLASS} />
      <span>{label}</span>
    </button>
  )
}

export function ContextMenu({
  x,
  y,
  isTrash,
  readonly,
  isUTools,
  hasDescription,
  onClose,
  onAction
}: ContextMenuProps) {
  const menuRef = useRef<HTMLDivElement | null>(null)
  const [isPositioned, setIsPositioned] = useState(false)
  const [style, setStyle] = useState<CSSProperties>({
    top: 0,
    left: 0,
    visibility: 'hidden'
  })

  const updatePosition = useCallback(() => {
    const el = menuRef.current
    if (!el) return

    const rect = el.getBoundingClientRect()
    const viewWidth = window.innerWidth
    const viewHeight = window.innerHeight

    let left = x
    let top = y

    if (left + rect.width > viewWidth - EDGE_GAP) {
      left = viewWidth - rect.width - EDGE_GAP
    }
    if (top + rect.height > viewHeight - EDGE_GAP) {
      top = y - rect.height
    }

    left = Math.max(EDGE_GAP, left)
    top = Math.max(EDGE_GAP, top)

    setStyle({
      top: `${Math.round(top)}px`,
      left: `${Math.round(left)}px`,
      visibility: 'visible'
    })
    setIsPositioned(true)
  }, [x, y])

  // 挂载 / 坐标变化后量取尺寸定位（等价旧版 nextTick + watch）
  useLayoutEffect(() => {
    setIsPositioned(false)
    updatePosition()
  }, [updatePosition])

  useEffect(() => {
    const handleClickOutside = (e: Event) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        onClose()
      }
    }
    const handleResize = () => updatePosition()

    document.addEventListener('click', handleClickOutside)
    document.addEventListener('contextmenu', handleClickOutside)
    document.addEventListener('scroll', handleClickOutside, true)
    window.addEventListener('resize', handleResize)

    return () => {
      document.removeEventListener('click', handleClickOutside)
      document.removeEventListener('contextmenu', handleClickOutside)
      document.removeEventListener('scroll', handleClickOutside, true)
      window.removeEventListener('resize', handleResize)
    }
  }, [onClose, updatePosition])

  const handleAction = (action: ContextMenuAction) => {
    onAction(action)
    onClose()
  }

  return createPortal(
    <div
      ref={menuRef}
      className={cn(
        'context-menu fixed z-[10000] w-[224px] bg-popover border border-border rounded-[11px] shadow-lg p-[5px] flex flex-col animate-[ctx-pop-in_0.12s_ease-out_forwards]',
        !isPositioned && 'pointer-events-none'
      )}
      style={style}
      onClick={(e) => e.stopPropagation()}
      onContextMenu={(e) => e.preventDefault()}
    >
      {!isTrash ? (
        <>
          <MenuItem icon={ExternalLink} label="打开链接" onClick={() => handleAction('open')} />

          {isUTools && (
            <MenuItem
              icon={Globe}
              label="使用 uTools 浏览器打开"
              onClick={() => handleAction('openInUtoolsBrowser')}
            />
          )}

          <MenuItem icon={Copy} label="复制链接" onClick={() => handleAction('copy')} />

          <MenuItem
            icon={FileText}
            label="复制描述"
            disabled={!hasDescription}
            onClick={() => handleAction('copyDescription')}
          />

          {!readonly && (
            <>
              <div className={DIVIDER_CLASS} />
              <MenuItem icon={Pencil} label="编辑" onClick={() => handleAction('edit')} />
              <MenuItem icon={Pin} label="置顶" onClick={() => handleAction('pin')} />
              <MenuItem icon={Folder} label="在分组中定位" onClick={() => handleAction('locate')} />
              <div className={DIVIDER_CLASS} />
              <MenuItem
                icon={Trash2}
                label="移到回收站"
                danger
                onClick={() => handleAction('remove')}
              />
            </>
          )}
        </>
      ) : (
        <>
          <MenuItem icon={CornerUpLeft} label="还原" onClick={() => handleAction('restore')} />
          <div className={DIVIDER_CLASS} />
          <MenuItem
            icon={Trash2}
            label="彻底删除"
            danger
            onClick={() => handleAction('remove')}
          />
        </>
      )}
    </div>,
    document.body
  )
}

export default ContextMenu
