// src/components/ResultToast.vue
<script setup lang="ts">
/**
 * 全局结果反馈 Toast
 * 
 * 【动画锚点规范】
 * - 动画从触发位置"生长"出来 (使用 @starting-style + allow-discrete)
 * - transform-origin 通过 CSS 变量 --origin-x/--origin-y 传入
 * - 调用 showToast 时传入 anchor: { element } 可指定触发位置
 */
import { computed } from 'vue'
import type { AnimationOrigin } from '@/composables/useUIManager'

type Variant = 'success' | 'info' | 'warning' | 'error'

const props = defineProps<{
  open: boolean
  title: string
  description?: string
  variant?: Variant
  icon?: string
  actionLabel?: string
  origin?: AnimationOrigin
}>()

const emit = defineEmits<{
  close: []
  action: []
}>()

const iconClass = computed(() => {
  if (props.icon) return props.icon
  const v = props.variant ?? 'info'
  if (v === 'success') return 'i-mdi-check-circle-outline text-primary'
  if (v === 'warning') return 'i-mdi-alert-outline text-yellow-500'
  if (v === 'error') return 'i-mdi-close-circle-outline text-destructive'
  return 'i-mdi-information-outline text-muted-foreground'
})

const MAX_TITLE_LEN = 50
const MAX_DESC_LEN = 300

const sanitizedTitle = computed(() => {
  const t = props.title || ''
  return t.length > MAX_TITLE_LEN ? t.slice(0, MAX_TITLE_LEN) + '…' : t
})

const sanitizedDescription = computed(() => {
  const d = props.description || ''
  return d.length > MAX_DESC_LEN ? d.slice(0, MAX_DESC_LEN) + '…' : d
})

// 始终在右上角
const positionClass = 'top-20 right-4'

// 动画原点 CSS 变量
const originStyle = computed(() => {
  const o = props.origin
  if (!o) return {}
  return {
    '--origin-x': o.x,
    '--origin-y': o.y
  }
})
</script>

<template>
  <Teleport to="body">
    <!-- 使用 hidden 属性配合 allow-discrete 实现入场/退场动画 -->
    <div
      class="toast-container"
      :class="positionClass"
      :style="originStyle"
      :hidden="!open || undefined"
    >
      <div class="flex gap-3" :class="description ? 'items-start' : 'items-center'">
        <span :class="[iconClass, 'text-lg shrink-0', description ? 'mt-0.5' : '']" />
        <div class="min-w-0 flex-1">
          <p class="text-sm font-medium text-foreground leading-tight">{{ sanitizedTitle }}</p>
          <p v-if="sanitizedDescription" class="text-xs text-muted-foreground mt-1 whitespace-pre-wrap break-words max-h-[120px] overflow-y-auto">{{ sanitizedDescription }}</p>
        </div>
        <Button variant="ghost" size="icon" class="h-7 w-7 shrink-0" title="关闭" @click="emit('close')">
          <span class="i-mdi-close text-sm text-muted-foreground" />
        </Button>
      </div>

      <div v-if="actionLabel || $slots.action" class="mt-3 flex items-center justify-end gap-2">
        <slot name="action" />
        <Button v-if="actionLabel" size="sm" variant="outline" class="h-7 px-3 text-xs" @click="emit('action')">
          {{ actionLabel }}
        </Button>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.toast-container {
  position: fixed;
  z-index: 20000;
  width: 320px;
  max-width: calc(100vw - 2rem);
  max-height: 200px;
  overflow-y: auto;
  border-radius: var(--radius-lg);
  border: 1px solid hsl(var(--border));
  background: hsl(var(--card));
  box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  backdrop-filter: blur(8px);
  padding: 1rem;
  pointer-events: auto;

  /* 动画属性 */
  opacity: 1;
  transform: scale(1);
  transform-origin: var(--origin-x, right) var(--origin-y, bottom);
  
  /* allow-discrete 让 display 属性也能过渡 */
  transition: 
    opacity 220ms cubic-bezier(0.16, 1, 0.3, 1),
    transform 220ms cubic-bezier(0.16, 1, 0.3, 1),
    display 220ms allow-discrete;

  /* 入场动画：首次渲染时的初始状态 */
  @starting-style {
    opacity: 0;
    transform: scale(0.92);
  }
}

/* 退场动画：hidden 状态 */
.toast-container[hidden] {
  display: block; /* 覆盖 hidden 默认的 display:none，让过渡生效 */
  opacity: 0;
  transform: scale(0.92);
  pointer-events: none;
  
  /* 延迟 display 切换，等动画完成 */
  transition: 
    opacity 180ms ease-in,
    transform 180ms ease-in,
    display 180ms allow-discrete;
}
</style>

// src/components/ResultToast.tsx
import { useMemo } from 'react'
import type { CSSProperties, ReactNode } from 'react'
import { createPortal } from 'react-dom'
import { Info, CheckCircle2, AlertTriangle, XCircle, X } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { AnimationOrigin } from '@/hooks/useUIManager'
import { cn } from '@/lib/utils'

/**
 * ResultToast（React 版）
 * --------------------------------------------------------------------------
 * 旧版 Vue Teleport + hidden + @starting-style 生长动画 → React createPortal +
 * hidden 属性 + .toast-container 样式（已迁移到 index.css）。i-ph-* 图标改用
 * lucide-react；origin 通过 --origin-x/--origin-y CSS 变量传入控制生长锚点。
 * 自定义 action 区域通过 actionSlot 传入（等价旧版具名插槽）。
 */
type Variant = 'success' | 'info' | 'warning' | 'error'

export interface ResultToastProps {
  open: boolean
  title: string
  description?: string
  variant?: Variant
  /** 可选的自定义图标组件，覆盖按 variant 推导的默认图标 */
  icon?: LucideIcon
  actionLabel?: string
  origin?: AnimationOrigin
  onClose: () => void
  onAction?: () => void
  /** 等价旧版具名插槽 #action，渲染在内置 actionLabel 按钮左侧 */
  actionSlot?: ReactNode
}

const MAX_TITLE_LEN = 50
const MAX_DESC_LEN = 300

const VARIANT_ICON: Record<Variant, { Icon: LucideIcon; color: string }> = {
  success: { Icon: CheckCircle2, color: 'text-primary' },
  info: { Icon: Info, color: 'text-muted-foreground' },
  warning: { Icon: AlertTriangle, color: 'text-yellow-500' },
  error: { Icon: XCircle, color: 'text-destructive' }
}

export function ResultToast({
  open,
  title,
  description,
  variant = 'info',
  icon,
  actionLabel,
  origin,
  onClose,
  onAction,
  actionSlot
}: ResultToastProps) {
  const { Icon, color } = VARIANT_ICON[variant]
  const ResolvedIcon = icon ?? Icon

  const sanitizedTitle = useMemo(() => {
    const t = title || ''
    return t.length > MAX_TITLE_LEN ? `${t.slice(0, MAX_TITLE_LEN)}…` : t
  }, [title])

  const sanitizedDescription = useMemo(() => {
    const d = description || ''
    return d.length > MAX_DESC_LEN ? `${d.slice(0, MAX_DESC_LEN)}…` : d
  }, [description])

  const originStyle = useMemo<CSSProperties>(() => {
    if (!origin) return {}
    return {
      ['--origin-x' as string]: origin.x,
      ['--origin-y' as string]: origin.y
    }
  }, [origin])

  return createPortal(
    <div
      className="toast-container top-20 right-4"
      style={originStyle}
      hidden={!open || undefined}
    >
      <div className={cn('flex gap-3', description ? 'items-start' : 'items-center')}>
        <ResolvedIcon className={cn('text-lg shrink-0 size-[18px]', icon ? '' : color, description && 'mt-0.5')} />
        <div className="min-w-0 flex-1">
          <p className="text-sm font-medium text-foreground leading-tight">{sanitizedTitle}</p>
          {sanitizedDescription && (
            <p className="text-xs text-muted-foreground mt-1 whitespace-pre-wrap break-words max-h-[120px] overflow-y-auto">
              {sanitizedDescription}
            </p>
          )}
        </div>
        <button
          type="button"
          title="关闭"
          className="h-7 w-7 shrink-0 inline-flex items-center justify-center rounded-md text-muted-foreground hover:bg-muted/70 hover:text-foreground transition-colors"
          onClick={onClose}
        >
          <X className="size-[14px]" />
        </button>
      </div>

      {(actionLabel || actionSlot) && (
        <div className="mt-3 flex items-center justify-end gap-2">
          {actionSlot}
          {actionLabel && (
            <button
              type="button"
              className="h-7 px-3 text-xs inline-flex items-center justify-center rounded-md border border-input bg-muted/35 text-foreground shadow-sm hover:bg-muted/60 transition-colors"
              onClick={onAction}
            >
              {actionLabel}
            </button>
          )}
        </div>
      )}
    </div>,
    document.body
  )
}

export default ResultToast
