// src/components/ui/image/Image.tsx
import { useState, type CSSProperties } from 'react'
import { ImageOff } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * Image —— Vue 自定义图片组件 → React 等价重写。
 * --------------------------------------------------------------------------
 * 行为等价：加载中显示骨架屏，失败时依 fallback 显示破图图标或留空。
 * - i-ph-image-broken-thin（UnoCSS presetIcons）→ lucide-react <ImageOff />。
 * - Vue emits error/load → React onError/onLoad 回调。
 */
export interface ImageProps {
  src?: string
  alt?: string
  width?: string | number
  height?: string | number
  className?: string
  /** 失败兜底：'icon' 显示破图图标（默认），'none' 留空。 */
  fallback?: 'icon' | 'none'
  onError?: () => void
  onLoad?: () => void
}

const toLength = (v?: string | number): string | undefined =>
  typeof v === 'number' ? `${v}px` : v

export function Image({
  src,
  alt,
  width,
  height,
  className,
  fallback = 'icon',
  onError,
  onLoad,
}: ImageProps) {
  const [hasError, setHasError] = useState(false)
  const [hasLoaded, setHasLoaded] = useState(false)

  const showSkeleton = !hasError && !hasLoaded && !!src

  const style: CSSProperties = {
    width: toLength(width),
    height: toLength(height),
  }

  const handleError = () => {
    setHasError(true)
    onError?.()
  }

  const handleLoad = () => {
    setHasLoaded(true)
    onLoad?.()
  }

  return (
    <div
      className={cn('relative overflow-hidden rounded-md bg-secondary', className)}
      style={style}
    >
      {showSkeleton && <div className="absolute inset-0 bg-muted animate-pulse" />}
      {!hasError && src ? (
        <img
          src={src}
          alt={alt}
          className="h-full w-full object-cover transition-all hover:scale-105"
          onError={handleError}
          onLoad={handleLoad}
        />
      ) : fallback !== 'none' ? (
        <div className="flex h-full w-full items-center justify-center text-muted-foreground">
          <ImageOff className="size-5" />
        </div>
      ) : null}
    </div>
  )
}

// src/components/ui/image/Image.vue
<script setup lang="ts">
import { type HTMLAttributes, ref, computed } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  src?: string
  alt?: string
  width?: string | number
  height?: string | number
  class?: HTMLAttributes['class']
  fallback?: 'icon' | 'none'
}>()

const emit = defineEmits<{
  (e: 'error'): void
  (e: 'load'): void
}>()

const hasError = ref(false)
const hasLoaded = ref(false)

const handleError = () => {
  hasError.value = true
  emit('error')
}

const handleLoad = () => {
  hasLoaded.value = true
  emit('load')
}

const showSkeleton = computed(() => !hasError.value && !hasLoaded.value && !!props.src)
</script>

<template>
  <div
    :class="cn('relative overflow-hidden rounded-md bg-secondary', props.class)"
    :style="{
      width: typeof width === 'number' ? width + 'px' : width,
      height: typeof height === 'number' ? height + 'px' : height
    }"
  >
    <div v-if="showSkeleton" class="absolute inset-0 bg-muted animate-pulse" />
    <img
      v-if="!hasError && src"
      :src="src"
      :alt="alt"
      class="h-full w-full object-cover transition-all hover:scale-105"
      @error="handleError"
      @load="handleLoad"
    />
    <div v-else-if="props.fallback !== 'none'" class="flex h-full w-full items-center justify-center text-muted-foreground">
      <span class="i-ph-image-broken-thin text-xl" />
    </div>
  </div>
</template>
